[es esm]

//OTHER SYSTEM STUFF
FO_64SYSTEM_AUTO = "Algunos cambios no se inicializan automáticamente";
FO_64SYSTEM_APPLY = "Presiona \"Aplicar cambios\" para que surtan efecto";
FO_64SYSTEM_RESTART = "Cualquier cambio aquí requiere reiniciar el nivel para funcionar.";
FO_64SYSTEM_APPLIED = "Aplicar cambios";

TXT_NO = "No";
TXT_YES = "Sí";
OPTVAL_ON = "ACTIVADO";
OPTVAL_OFF = "DESACTIVADO";

FO_DEFAULT = "Predeterminado";
FO_CLASSICAL = "Clásico";
FO_SWC = "Visión de SWC";

FO_ENABLED = "Habilitado";
FO_DISABLED = "Deshabilitado";
FO_ALTERNATIVE = "Alternativo";
FO_GEC = "GEC (predeterminado)";

FO_RANDOM = "Aleatorio";

RANDOM_NO_ANNIHILATOR = "Aleatorio (sin Aniquilador)";
RANDOM_NO_INFERNAL = "Aleatorio (sin Infernal)";

RANDOM_NO_MOTHER = "Aleatorio (sin Madre Demonio)";
RANDOM_NO_ERADICATOR = "Aleatorio (sin Erradicador)";

RANDOM_NO_NIGHTCRAWLER = "Aleatorio (sin Merodeador Nocturno)";
RANDOM_NO_IMPALER = "Aleatorio (sin Empalador)";

RANDOM_NO_STALKER = "Aleatorio (sin Acechador)";
RANDOM_NO_FORGOTTEN = "Aleatorio (sin Olvidado)";

RANDOM_NO_HELLHOUND = "Aleatorio (sin Sabueso del Infierno)";
RANDOM_NO_BELPHEGOR = "Aleatorio (sin Belfegor)";

RANDOM_NO_ACID = "Aleatorio (sin Demonio Ácido)";
RANDOM_NO_BUTCHER = "Aleatorio (sin Carnicero)";

RANDOM_NO_CACO_NIGHTMARE = "Aleatorio (sin variante Pesadilla)";
RANDOM_NO_FALLEN = "Aleatorio (sin Caído)";

RANDOM_NO_SPECTRE_NIGHTMARE = "Aleatorio (sin variante Pesadilla)";
RANDOM_NO_WRAITH = "Aleatorio (sin Espectro Voraz)";

RANDOM_NO_IMP_NIGHTMARE = "Aleatorio (sin variante Pesadilla)";
RANDOM_NO_HARVESTER = "Aleatorio (sin Cosechador)";

RANDOM_NO_SSGGUY = "Aleatorio (sin SSG)";
RANDOM_NO_BFG_GUY = "Aleatorio (sin BFG)";

RANDOM_NO_WIZARD = "Aleatorio (sin Mago de Carne)";
RANDOM_NO_HELLSTORM = "Aleatorio (sin Tormenta del Infierno)";

FO_HUSK_1 = "1 Cascarón";
FO_HUSK_2 = "2 Cascarones";
FO_HUSK2_CARRION1 = "2 Cascarones y 1 Carroñero";
FO_HUSK3_CARRION2 = "3 Cascarones y 1 Carroñero";

FO_CHAINGUN = "Ametralladora";
FO_RIFLE = "Rifle de Asalto";
FO_SMG = "Subfusil";
FO_BFG = "BFG9000";
FO_UNMAKER = "Deshacedor";
FO_LASER = "Rifle Láser";
FO_PLASMA = "Rifle de Plasma";
FO_GAUSS = "Cañón Gauss";

FO_BLOOD_LOW = "Bajo";
FO_BLOOD_NORMAL = "Normal";
FO_BLOOD_LOT = "Mucho";
FO_BLOOD_COMIC = "Cómico";
FO_BLOOD_MAX = "Máximo";

//////////////////////////////////////////////////////////////////
//HUD

HUD_ARMOR = "Armadura";
HUD_HEALTH = "Salud";

//////////////////////////////////////////////////////////////////
//weapon, item & misc messages

NEED_FLASHLIGHT = "¡Necesitas una linterna! Se encuentra en las mochilas";
WM_NOSTAMINA = "¡Sin energía suficiente!";
WM_NEED_SILENCER = "¡Necesitas un silenciador! Se encuentra en las mochilas";
WM_CHAINSAW_SSG_NONE = "¡Necesitas una súper escopeta!";
WM_CHAINSAW_SSG = "¡La súper escopeta necesita recargarse!";
WM_CHAINGUNSPIN = "Nadie en su sano juicio tocaría una ametralladora girando.";
WM_NOTENOUGHAMMO = "¡Sin suficiente munición!";
WM_ROCKETROUND = "Rondas de cohete activadas";
WM_MORTARROUND = "Rondas de mortero activadas";
WM_SPECIAL = "Acción especial de arma disponible";
WM_NOMINES = "¡Sin minas en el inventario!";
WM_NOTENOUGHDEMONART = "¡Sin suficientes artefactos demoníacos!";
WM_AUTOFIRE = "Modo de fuego automático";
WM_BURSTFIRE = "Modo de ráfaga";
UN_REGULAR = "Modo regular";
UN_UNMAKE = "Modo deshacer";
UN_HELLTIME = "Modo tiempo infernal";
UN_TIMESTOP = "¡El tiempo se detiene por completo!";
UN_NOTENOUGHSOULS = "¡Sin suficientes almas!";
UN_NOTENOUGHESSENCE = "¡Sin suficiente esencia demoníaca!";
SH_NEEDBANDAGES = "¡Sin suficientes vendajes!";
SH_HEALTY = "Estás sano";
SH_BERSERKLIMIT = "¡No puedes usar más de una jeringa berserk!";
SH_NOSYRINGES = "¡No tienes jeringas berserk!";

//////////////////////////////////////////////////////////////////
//Tags for Classes

FO_TAG_CLASS_CLASSIC = "Clásico";
FO_TAG_MODERN = "Moderno";
FO_TAG_CLASS_TACTICAL = "Táctico";

//////////////////////////////////////////////////////////////////
//Tags for Dificulties

FO_TAG_BABY = "¡Sé gentil!";
FO_TAG_BABY_TXT = "Equivalente a 'Soy muy joven para morir' (factor de munición x2)";
FO_TAG_EASY = "¡Vengan por más!";
FO_TAG_EASY_TXT = "Equivalente a 'Oye, no tan rudo'";
FO_TAG_NORMAL = "¡Doom es mío!";
FO_TAG_NORMAL_TXT = "Equivalente a 'Hazme sufrir'";
FO_TAG_HARD = "¡Mírame morir!";
FO_TAG_HARD_TXT = "Equivalente a 'Ultraviolencia'";
FO_TAG_HARDER = "¡Mírame morir+!";
FO_TAG_HARDER_TXT = "Equivalente a 'Ultraviolencia+', proyectiles enemigos acelerados, aparición de armas del multijugador";
FO_TAG_NIGHTMARE = "¡Pesadilla!";
FO_TAG_NIGHTMARE_TXT = "Habilidades de monstruos = proyectiles rápidos, +25% de salud y más agresivos";
FO_TAG_SURVIVAL = "¡Supervivencia!";
FO_TAG_SURVIVAL_TXT = "Habilidades de monstruos = +25% de salud (curación manual del jugador).";
FO_TAG_REALISM = "¡Supervivencia! (Realista)";
FO_TAG_REALISM_TXT = "Habilidades de monstruos = proyectiles rápidos, -70% de salud e infligen daño x5 (curación manual del jugador)";

FO_TAG_HARDER_RELOAD_MESSAGE = "El mapa se ha reiniciado durante la emulación de multijugador activada";

//////////////////////////////////////////////////////////////////
//Option values

FO_OP_BD64 = "Brutal Doom 64";
FO_OP_KICK = "Patada";
FO_OP_TOSS = "Lanzar mina";
FO_OP_PLACE = "Colocar mina";
FO_OP_SPECIAL = "Acción especial de arma";
FO_OP_FLASH = "Alternar linterna";

//////////////////////////////////////////////////////////////////
//menus

FO_MNU_NEWGAME = "NUEVA PARTIDA";
FO_MNU_LOAD = "CARGAR PARTIDA";
FO_MNU_SAVE = "GUARDAR PARTIDA";
FO_MNU_OPTIONS = "OPCIONES";
FO_MNU_64OPTIONS = "Opciones de BD64";
FO_MNU_READ = "LEE ESTO";
FO_MNU_QUIT = "SALIR DEL JUEGO";

FO_MNU_CLASS = "Elige tu clase:";

FO_64OPTIONS_MAIN = "OPCIONES DE BRUTAL DOOM 64";

FO_64OPTIONS_MAIN_TXT1 = "Algunos cambios no se inicializan automáticamente";
FO_64OPTIONS_MAIN_TXT2 = "Presiona \"Aplicar cambios\" para que los cambios surtan efecto";

FO_64OPTIONS_PRESET = "---------- Ajustes Preestablecidos ----------";

FO_64MNU_LAST = "Último preajuste usado =";

FO_64MNU_BEFORE = "Debes estar dentro de un nivel antes de presionar los botones";
FO_64MNU_APPLY = "También debes salir del menú cada vez que apliques un preajuste";
FO_64MNU_COMFIRM = "La opción superior es solo una confirmación de que el preajuste se aplicó correctamente";
FO_64MNU_NOTHING = "no hace nada";

FO_64MNU_DEFAULT = "Predeterminado";
FO_64MNU_DEFAULT_TXT = "Las opciones predeterminadas del mod";
FO_64MNU_CLASSICAL = "Clásico";
FO_64MNU_CLASSICAL_TXT = "Ajusta la configuración para ser lo más original posible";
FO_64MNU_SWC = "Visión de SWC";
FO_64MNU_SWC_TXT1 = "Añade nuevos monstruos y armas con ajustes equilibrados,";
FO_64MNU_SWC_TXT2 = "como el creador juega a su propio mod";
FO_64MNU_RANDOM = "Aleatorizador de Generadores";
FO_64MNU_RANDOM_TXT1 = "Para configurar todos los generadores de monstruos/armas/objetos en aleatorio, presiona esto";

FO_64OPTIONS_OPTIONS = "---------- Opciones ----------";

FO_64MNU_OTHER_ITEMS = "Otras opciones de objetos/armas";
FO_64MNU_OHTHER_MONSTER = "Otras opciones de monstruos";
FO_64MNU_PERFORMANCE = "Rendimiento y opciones varias";
FO_64MNU_LEVEL_OPTIONS = "Opciones de mapa";

FO_64OPTIONS_GAMEPLAY = "---------- Jugabilidad ----------";

FO_64MNU_WEAPONS_SPAWN = "Opciones de generador de objetos/armas";
FO_64MNU_MONSTER_SPAWN = "Opciones de generador de monstruos";
FO_64MNU_ENGINE = "Atajos de motor (GZD, Zand)";

FO_64MNU_ITEMS_WEAPONS_SPAWN = "Opciones de generador de objetos/armas";

FO_64MNU_ITEMS_WEAPONS_SPAWN_TXT1 = "Opciones para elegir reemplazos de armas y potenciadores";
FO_64MNU_ITEMS_WEAPONS_SPAWN_TXT2 = "o configurarlos para que aparezcan al azar";

FO_64MNU_BONUSSPAWNER = "Generador de Bonificaciones";
FO_64MNU_BONUS = "Predeterminado = Bonificación regular";
FO_64MNU_BONUS_TXT = "(las pociones del infierno combinan armadura y salud)";

FO_64MNU_POWERUP_SPAWNER = "Generador de Potenciadores";
FO_64MNU_POWERUP = "Predeterminado = Potenciadores";
FO_64MNU_POWERUP_NOTE = "(Para mapas de D64 se recomienda dejarlo en Potenciadores)";

FO_64MNU_PLASMASPAWNER = "Generador de Rifle de Plasma";
FO_64MNU_PLASMA = "Predeterminado = Rifle de Plasma";

FO_64MNU_BFGSPAWNER = "Generador de BFG 9000";
FO_64MNU_BFG = "Predeterminado = BFG 9000";

FO_64MNU_CHAINGUNSPAWNER = "Generador de Ametralladora";
FO_64MNU_CHAINGUN = "Predeterminado = Ametralladora";

FO_64MNU_OTHER_ITEMS_SPAWN = "Otras opciones de objetos/armas";

FO_64MNU_WEAPON_FUNCTION = "---------- Funciones de Armas ----------";

FO_64MNU_WARMUP = "Activar animaciones de desenfunde de arma =";
FO_64MNU_WARMUP_TXT = "Muestra animaciones al recoger un arma por primera vez (SOLO modos táctico/moderno).";
FO_64MNU_CLASSIC_CHAINSAW = "Apariencia de Motosierra clásica para Táctico/Moderno =";
FO_64MNU_CLASSIC_CHAINGUN = "Apariencia de Ametralladora clásica para Táctico/Moderno =";
FO_64MNU_CLASSIC_ROCKET = "Apariencia de Lanzacohetes clásico para Táctico/Moderno =";
FO_64MNU_CLASSIC_SWITCH = "Opciones para cambiar entre armas clásicas o modernizadas.";

FO_64MNU_SKIP_RELOAD = "Omitir secuencias de recarga de armas (Presiona \"Aplicar cambios\") =";
FO_64MNU_SKIP_RELOAD_TXT = "Omitir secuencias de animación de recarga (SOLO modos táctico/moderno).";

FO_64MNU_LOWAMMO = "Efecto de sonido de munición baja =";
FO_64MNU_LOWAMMO_TXT1 = "Te permite activar o desactivar la advertencia sonora cuando la munición es muy baja.";
FO_64MNU_LOWAMMO_TXT2 = "(SOLO modos táctico/moderno)";

FO_64MNU_SWITCH_FIST = "Cambiar a puños al recoger Berserk =";
FO_64MNU_SWITCH_FIST_TXT = "Opción para desactivar el cambio a puños al recoger el paquete berserk.";

FO_64MNU_SKINS = "---------- Aspectos de Armas y Objetos ----------";

FO_64MNU_SKIN_LASER = "Aspecto alternativo del Láser =";
FO_64MNU_SKIN_ITEM = "Sprites de objetos al recoger =";
FO_64MNU_SKIN_HEALTH = "Botiquines y Berserk alternativos =";
FO_64MNU_SKIN_ALPHA = "Objetos de la versión Alpha =";
FO_64MNU_SKIN_ALPHA_TXT = "Opciones para diseños alternativos o de versiones alpha para objetos y armas.";

FO_64MNU_OTHER = "---------- Otros ----------";

FO_64MNU_FLASHLIGHT = "Comenzar con linterna =";

FO_MONSTER_SPAWN = "Opciones de generador de monstruos";
FO_MONSTER_SPAWN_TXT1 = "Estas opciones permiten configurar los reemplazos de monstruos a versión pesadilla,";
FO_MONSTER_SPAWN_TXT2 = "monstruos exiliados o extra, o configurarlos para que aparezcan al azar";

FO_SPAWN_ZOMBIEMAN = "Generador de Zombie con pistola =";
FO_SPAWN_ZOMBIEMAN_TXT = "Porcentaje aleatorio de Zombie con pistola =";
FO_SPAWN_SHOTGUNGUY = "Generador de Zombie con escopeta =";
FO_SPAWN_SHOTGUNGUY_TXT = "Porcentaje aleatorio de Zombie con escopeta =";
FO_SPAWN_COMMANDO = "Generador de Zombie con ametralladora =";
FO_SPAWN_COMMANDO_TXT = "Porcentaje aleatorio de Zombie con ametralladora =";
FO_SPAWN_IMP = "Generador de Imp =";
FO_SPAWN_IMP_TXT = "Porcentaje aleatorio de Imp =";
FO_SPAWN_PINKY = "Generador de Demonio =";
FO_SPAWN_PINKY_TXT = "Porcentaje aleatorio de Demonio =";
FO_SPAWN_SPECTRE = "Generador de Espectro =";
FO_SPAWN_SPECTRE_TXT = "Porcentaje aleatorio de Espectro =";
FO_SPAWN_CACO = "Generador de Cacodemonio =";
FO_SPAWN_CACO_TXT = "Porcentaje aleatorio de Cacodemonio =";
FO_SPAWN_SOUL = "Generador de Alma Perdida =";
FO_SPAWN_SOUL_TXT1 = "Porcentaje aleatorio de Alma Perdida =";
FO_SPAWN_SOUL_TXT2 = "(El Elemental de Dolor/Agonía puede invocarlas según estos valores)";
FO_SPAWN_KNIGHT = "Generador de Caballero del Infierno =";
FO_SPAWN_KNIGHT_TXT = "Porcentaje aleatorio de Caballero del Infierno =";
FO_SPAWN_UNDEAD = "Generador de Revenant =";
FO_SPAWN_UNDEAD_TXT = "Porcentaje aleatorio de Revenant =";
FO_SPAWN_BARON = "Generador de Barón del Infierno =";
FO_SPAWN_BARON_TXT = "Porcentaje aleatorio de Barón del Infierno =";
FO_SPAWN_FATSO = "Generador de Mancubos =";
FO_SPAWN_FATSO_TXT = "Porcentaje aleatorio de Mancubos =";
FO_SPAWN_ELEMENTAL = "Generador de Elemental de Dolor =";
FO_SPAWN_ELEMENTAL_TXT = "Porcentaje aleatorio de Elemental de Dolor =";
FO_SPAWN_VILE = "Generador de Arch-vile =";
FO_SPAWN_VILE_TXT = "Porcentaje aleatorio de Arch-vile =";
FO_SPAWN_CYBERDEMON = "Generador de Ciberdemonio =";
FO_SPAWN_CYBERDEMON_TXT = "Porcentaje aleatorio de Ciberdemonio =";
FO_SPAWN_MASTERMIND = "Generador de Cerebro Arácnido =";
FO_SPAWN_MASTERMIND_TXT = "Porcentaje aleatorio de Cerebro Arácnido =";
FO_SPAWN_HUSK = "Multiplicador de Horda Zombie Cascarón =";
FO_SPAWN_HUSK_TXT1 = "Porcentaje aleatorio de Horda Zombie Cascarón =";
FO_SPAWN_HUSK_TXT2 = "Opción para generar Cascarones y Carroñeros cerca de cadáveres de zombies";
FO_SPAWN_HUSK_TXT3 = "Desactivado por defecto";
FO_SPAWN_SETTING = "(Configuración recomendada x3, x4 o Aleatorio)";

FO_MONSTER_OTHER = "Otras opciones de monstruos";

FO_MONSTER_SKIN = "---------- Aspectos de Monstruos ----------";

FO_MONSTER_HELLHOUND = "Estilo de Sabueso del Infierno =";
FO_MONSTER_HELLHOUND_TXT1 = "Si seleccionaste \"Aleatorio (sin Barón)\"";
FO_MONSTER_HELLHOUND_TXT2 = "y desactivaste el aspecto de Sabueso del Infierno";
FO_MONSTER_HELLHOUND_TXT3 = "recibirás \"Aleatorio (sin Sabueso del Infierno)\"";

FO_MONSTER_CACO = "Estilo de Cacodemonio =";

FO_OPTION_MAP = "---------- Selección de Conjunto de Mapas ----------";

FO_MAP_SELECT = "Seleccionar conjunto de mapas =";
FO_MAP_SELECT_TXT1 = "Esta opción no es automática y debe configurarse manualmente";
FO_MAP_SELECT_TXT2 = "antes de comenzar una nueva partida en uno de los WADs compatibles";
FO_MAP_SELECT_TXT3 = "Puedes usar Doom 2 en WADs no compatibles";

FO_MAP_PROP = "---------- Reemplazo de Decoraciones de Mapa ----------";

FO_PROP_INFECTED = "Cadáver de Marine Infectado =";
FO_PROP_INFECTED_TXT = "Reemplaza cadáveres de marines por monstruos tipo 'La Cosa'.";
FO_PROP_GHOST = "Modo Poltergeist =";
FO_PROP_GHOST_TXT1 = "Reemplaza objetos del mapa con objetos poltergeist hostiles.";
FO_PROP_GHOST_TXT2 = "(los poltergeists son objetos del mapa hostiles que pueden atacar al jugador)";

FO_PERFORMANCE_MISK = "Opciones de rendimiento y varios";
FO_PERFORMANCE_MISK_TXT = "Activa esta opción SOLO si albergas un servidor de multijugador.";
FO_PERFORMANCE_MISK_TXT2 = "(activar esta opción generará un mensaje de error si usas GZDoom)";

FO_OPTION_PERFORMANCE = "---------- Rendimiento y Sangre ----------";

FO_OPTION_PERFORMANCE_CLIENT = "Seleccionar cantidad de sangre =";
FO_OPTION_PERFORMANCE_FLATS = "Eliminar sangre en superficies planas (30s) =";
FO_OPTION_PERFORMANCE_DECALS = "Activar marcas de disparos/explosiones en suelo y techo =";
FO_OPTION_PERFORMANCE_FOG = "Opciones de niebla ligera y halos =";
FO_OPTION_PERFORMANCE_TORCH = "Activar antorchas de estilo clásico (Requiere reiniciar mapa) =";
FO_OPTION_PERFORMANCE_SPLASH = "Desactivar salpicaduras de líquidos =";

FO_OPTION_HUD = "---------- HUD ----------";

FO_OPTION_HUD_STYLE = "Estilo de HUD =";
FO_OPTION_HUD_SCREEN = "Activar efectos en pantalla de HUD =";
FO_OPTION_HUD_BLOOD = "Activa efectos en pantalla como salpicaduras de sangre y agujeros de bala.";
FO_OPTION_HUD_TRAILS = "Activar rastro de salpicaduras de sangre en pantalla =";
FO_OPTION_HUD_SPLASH = "Los monstruos sangrando de cerca crearán salpicaduras en el HUD.";
FO_OPTION_HUD_SPLASH_TXT1 = "(Si los efectos de pantalla están desactivados, esta opción también lo estará)";
FO_OPTION_HUD_SPLASH_TXT2 = "(No funciona para el modo de efectos de pantalla de BDv21)";

FO_OPTION_SOUND = "---------- Sonidos ----------";

FO_OPTION_SOUND_FOOTS = "Activar sonidos de pisadas =";

FO_ENGINE_OPTION = "Atajos de opciones del motor";
FO_ENGINE_OPTION_TXT = "Opciones de ZDoom, disponibles aquí para tu conveniencia";
FO_ENGINE_CLIPPING = "Ajustar recorte de sprites";
FO_ENGINE_CROSSHAIR = "Forzar miras de ZDoom";
FO_ENGINE_JUMP = "Permitir saltar";
FO_ENGINE_CROUCH = "Permitir agacharse";
FO_ENGINE_FREELOOK = "Permitir vista libre";
FO_ENGINE_BOBBING = "Intensidad del balanceo de movimiento";
FO_ENGINE_PARTICULES = "Límite de partículas";
FO_ENGINE_INPUT = "ingresar valor manualmente";
FO_ENGINE_MAX = "Límite de marcas de impacto";
FO_ENGINE_DECALS = "ingresar valor manualmente";
FO_ENGINE_FPS = "Contador de FPS";
FO_ENGINE_DISCORD = "Discord Rich Presence";
FO_ENGINE_DISCORD_TXT = "(Discord Rich Presence no es compatible con Zandronum)";
FO_ENGINE_LANGUAGE_TXT = "(El idioma ruso no es compatible con Zandronum)";

FO_ENGINE_GIBS = "Cantidad en cola de vísceras";
FO_ENGINE_GIBS_TXT1 = "Limita cuántas vísceras se generarán en cualquier momento.";
FO_ENGINE_GIBS_TXT2 = "Aumentar este valor solo afectará la cantidad máxima";
FO_ENGINE_GIBS_TXT3 = "en el mundo, no por monstruo.";
FO_ENGINE_GIBS_MAX = "Máximo de vísceras";

//////////////////////////////////////////////////////////////////

FO_EMPTYSTRING = "ranura vacía";

//////////////////////////////////////////////////////////////////
//health & armor pickups

FO_GOTARMBONUS = "¡Recogiste una bonificación de armadura!";
FO_GOTARMOR = "¡Recogiste una armadura!";
FO_GOTMEGA = "¡Conseguiste la Megaarmadura!";

FO_GOTHTHBONUS = "¡Recogiste una bonificación de salud!";
FO_GOTHPOTION = "¡Recogiste una Poción del Infierno!";
FO_GOTSTIM = "¡Recogiste un estimulante!";
FO_GOTMEDINEED = "¡Recogiste un botiquín que ¡REALMENTE necesitabas!";
FO_GOTMEDIKIT = "¡Recogiste un botiquín!";

//////////////////////////////////////////////////////////////////
//powerup pickups

FO_GOTINVUL = "¡Invulnerabilidad!";
FO_GOTSUPER = "¡Supercarga!";
FO_GOTMSPHERE = "¡Megaesfera!";
FO_GOTINVIS = "¡Invisibilidad parcial!";
FO_GOTSUIT = "¡Traje de protección antirradiación!";
FO_GOTVISOR = "¡Visor de amplificación de luz!";
FO_GOTMAP = "¡Mapa del área!";
FO_GOTBERSERK = "¡Berserk!";
FO_GOT_SCANNER = "¡Escáner de área avanzado!";

//////////////////////////////////////////////////////////////////
//key pickups

FO_GOTBLUECARD = "Recogiste una tarjeta azul.";
FO_GOTYELWCARD = "Recogiste una tarjeta amarilla.";
FO_GOTREDCARD = "Recogiste una tarjeta roja.";
FO_GOTBLUESKUL = "Recogiste una calavera azul.";
FO_GOTYELWSKUL = "Recogiste una calavera amarilla.";
FO_GOTREDSKUL = "Recogiste una calavera roja.";

//////////////////////////////////////////////////////////////////
//demon key pickups

FO_GOTDEMON_ORANGE = "Sientes que esto no debía ser tocado.";
FO_GOTDEMON_PURPLE = "Debe servir para algo...";
FO_GOTDEMON_BLU = "Sea lo que sea, no pertenece a este mundo.";
FO_GOTDEMON_GREEN = "Parece algún tipo de llave....";
FO_GOTDEMON_RED = "¿Para qué se usa esto?";

//////////////////////////////////////////////////////////////////
//ammo & misc item pickups

FO_GOTBACKPACK = "¡Conseguiste la mochila!";
FO_GOTBACKPACK2 = "¡Recogiste una mochila llena de munición y un silenciador!";
FO_GOTBACKPACK3 = "¡Recogiste una mochila llena de munición y una linterna!";
FO_GOTBACKPACK4 = "¡Recogiste una mochila llena de munición, un silenciador y una linterna!";
FO_GOTCLIP = "Recogiste un cargador de balas.";
FO_GOTCLIPBOX = "Recogiste una caja de balas.";
FO_GOTCLIPBOX2 = "Recogiste una caja de balas de alto calibre.";
FO_GOTSHELLS = "Recogiste cartuchos de escopeta.";
FO_GOTSHELLBOX = "Recogiste una caja de cartuchos de escopeta.";
FO_GOTROCKET = "Recogiste un cohete.";
FO_GOTROCKBOX = "Recogiste una caja de cohetes.";
FO_GOTCELL = "Recogiste una celda de energía.";
FO_GOTCELLBOX = "Recogiste un paquete de celdas de energía.";
FO_GOTSAWGAS = "Recogiste una lata de gasolina.";
FO_GOTSOUL = "Alma recolectada";
FO_GOTESSENSE = "Esencia demoníaca recolectada";
FO_GOTESSENSE2 = "Gran esencia demoníaca recolectada";
FO_GOTBANDAGES = "Recogiste algunos vendajes.";
FO_GOTSYRINGE = "Recogiste una jeringa Berserk.";
FO_SCAVENGE1 = "Rescatas 10 vendajes de este botiquín.";
FO_SCAVENGE2 = "Rescatas 25 vendajes de este botiquín.";
FO_SCAVENGE3 = "Rescatas una jeringa Berserk de este paquete Berserk.";
FO_GOTSILECER = "¡Recogiste un silenciador!";
FO_GOTFLASHLIGHT = "¡Recogiste una linterna!";
BD64_GOTMINES = "¡Recogiste una mina explosiva!";

//////////////////////////////////////////////////////////////////
//weapon pickups

//Slot 1
BD64_GOTCHAINSAW = "¡Una motosierra! ¡A buscar carne fresca! (Ranura 1)";
//Slot 2
BD64_GOTPISTOL = "¡Recogiste la pistola! (Ranura 2)";
BD64_GOTSMG = "¡Recogiste el subfusil! (Ranura 2)";
BD64_GOTMP40 = "¡Recogiste la MP40! (Ranura 2)";
//Slot 3
BD64_GOTSHOTGUN = "¡Recogiste la escopeta! (Ranura 3)";
BD64_GOTSHOTGUN2 = "¡Recogiste la súper escopeta! (Ranura 3)";
//Slot 4
BD64_GOTRIFLE = "¡Recogiste un rifle de asalto! (Ranura 4)";
BD64_GOTCHAINGUN = "¡Recogiste la ametralladora! (Ranura 4)";
//Slot 5
BD64_GOTLAUNCHER = "¡Recogiste el lanzacohetes! (Ranura 5)";
//Slot 6
BD64_GOTPLASMA = "¡Recogiste el rifle de plasma! (Ranura 6)";
BD64_GOTGAUSS = "¡Recogiste el cañón Gauss! (Ranura 6)";
//Slot 7
BD64_GOTBFG9000 = "¡Recogiste la BFG9000! Oh, sí. (Ranura 7)";
//Slot 8
BD64_GOTUNMAKER = "¡Qué diablos es esto! (Ranura 8)";
//Slot 9
BD64_GOTLASER = "¡Recogiste el rifle láser! (Ranura 9)";

//////////////////////////////////////////////////////////////////
//weapon tags

FO_TAG_DEFAULT = "Arma sin nombre";
//1
FO_TAG_FIST = "Puños";
FO_TAG_CHAINSAW = "Motosierra";
FO_TAG_PORTMEDIKIT = "Botiquín portátil";
//2
FO_TAG_PISTOL = "Pistola";
FO_TAG_SMG = "Subfusil";
FO_TAG_MP40 = "MP40";
//3
FO_TAG_SHOTGUN = "Escopeta";
FO_TAG_SUPERSHOTGUN = "Súper escopeta";
//4
FO_TAG_RIFLE = "Rifle de asalto";
FO_TAG_CHAINGUN = "Ametralladora";
//5
FO_TAG_ROCKETLAUNCHER = "Lanzacohetes";
//6
FO_TAG_PLASMARIFLE = "Rifle de plasma";
FO_TAG_GAUSS = "Cañón Gauss";
//7
FO_TAG_BFG9000 = "BFG9000";
//8
FO_TAG_UNMAKER = "Deshacedor";
//9
FO_TAG_LASER = "Rifle láser";

//////////////////////////////////////////////////////////////////
//ammo & misc item tags

FO_TAG_BACKPACK1 = "Mochila";
FO_TAG_BACKPACK2 = "Mochila y silenciador";
FO_TAG_BACKPACK3 = "Mochila y linterna";
FO_TAG_BACKPACK4 = "Mochila, linterna y silenciador";
FO_TAG_CLIP = "Cargador de balas";
FO_TAG_CLIPBOX = "Caja de balas";
FO_TAG_CLIPBOX2 = "Caja de balas de alto calibre";
FO_TAG_SHELL = "Cartuchos de escopeta";
FO_TAG_SHELLBOX = "Caja de cartuchos de escopeta";
FO_TAG_ROCKET = "Cohete";
FO_TAG_ROCKBOX = "Caja de cohetes";
FO_TAG_CELL = "Celda de energía";
FO_TAG_CELLBOX = "Paquete de celdas de energía";
FO_TAG_SOUL = "Alma";
FO_TAG_ESSENSE = "Esencia demoníaca";
FO_TAG_ESSENSE2 = "Gran esencia demoníaca";
FO_TAG_BANDAGES = "Vendajes";
FO_TAG_SYRINGE = "Jeringa Berserk";
FO_TAG_SAWGAS = "Lata de gasolina";
FO_TAG_MINES = "Mina explosiva";
FO_TAG_SILENCER = "Silenciador";
FO_TAG_FLASHLIGHT = "Linterna";

//////////////////////////////////////////////////////////////////
//health and armor tags

FO_TAG_HBONUS = "Bonificación de salud";
FO_TAG_HPOTION = "Poción del Infierno";
FO_TAG_STIM = "Estimulante";
FO_TAG_MEDIKIT = "Botiquín";

FO_TAG_ARMBONUS = "Bonificación de armadura";
FO_TAG_ARMOR = "Armadura verde";
FO_TAG_MEGA = "Armadura azul";

//////////////////////////////////////////////////////////////////
//powerup tags

FO_TAG_INVUL = "Esfera de Invulnerabilidad";
FO_TAG_SUPER = "Esfera de Almas";
FO_TAG_MSPHERE = "Megaesfera";
FO_TAG_INVIS = "Esfera de Invisibilidad Parcial";
FO_TAG_SUIT = "Traje de protección antirradiación";
FO_TAG_VISOR = "Visor de visión nocturna";
FO_TAG_MAP = "Mapa del área";
FO_TAG_BERSERK = "Paquete Berserk";
FO_TAG_SCANNER = "Escáner de área avanzado";

//////////////////////////////////////////////////////////////////
//demon keys tags

FO_TAG_DEMON_ORANGE = "Llave demoníaca naranja";
FO_TAG_DEMON_PURPLE = "Llave demoníaca púrpura";
FO_TAG_DEMON_BLUE = "Llave demoníaca cian";
FO_TAG_DEMON_GREEN = "Llave demoníaca exiliada verde";
FO_TAG_DEMON_RED = "Llave demoníaca exiliada roja";

//////////////////////////////////////////////////////////////////
//key tags

FO_TAG_BLUECARD = "Tarjeta azul";
FO_TAG_YELWCARD = "Tarjeta amarilla";
FO_TAG_REDCARD = "Tarjeta roja";
FO_TAG_GOTBLUESKUL = "Calavera azul";
FO_TAG_GOTYELWSKUL = "Calavera amarilla";
FO_TAG_GOTREDSKUL = "Calavera roja";

//////////////////////////////////////////////////////////////////
//weapons obituaries

FO_OB_RICOCHET = "%o comió plomo.";
FO_OB_MPKICK = "%o probó la bota de %k.";
FO_OB_MPSLIDEKICK = "%o tropezó con la barrida de %k.";

FO_OB_MPFIST = "%o probó el puño de %k.";
FO_OB_MPCHAINSAW = "%o fue destrozado por la motosierra de %k.";
FO_OB_MPPISTOL = "%o recibió cosquillas de la pistolita de %k.";
FO_OB_MPSMG = "%o fue acribillado por el subfusil de %k.";
FO_OB_MPRIFLE = "%o fue abatido por el rifle de asalto de %k.";
FO_OB_MP40 = "%o fue acribillado por %k.";
FO_OB_MPSHOTGUN = "%o probó la escopeta de %k.";
FO_OB_MPSSHOTGUN = "%o fue reventado por la súper escopeta de %k.";
FO_OB_MPCHAINGUN = "%o fue masacrado por la ametralladora de %k.";
FO_OB_MPROCKET = "%o se montó en el cohete de %k.";
FO_OB_MINES = "%o fue despedazado por la mina de %k.";
FO_OB_MPPLASMARIFLE = "%o fue derretido por el rifle de plasma de %k.";
FO_OB_GAUSS = "%o fue atravesado por el cañón Gauss de %k.";
FO_OB_MPBFG_BOOM = "%o fue pulverizado por la BFG de %k.";
FO_OB_MPBFG_BETA = "%o fue obliterado por la BFG de %k.";
FO_OB_LASER = "%o fue achicharrado por el rifle láser de %k.";
FO_OB_LASERBLAST = "%o fue desintegrado por el rifle láser de %k.";
FO_OB_MPUNMAKER = "%o fue deshecho por %k.";

//////////////////////////////////////////////////////////////////
//demon tags

FO_TAG_STEALTHBABY = "Aracnotrón Sigiloso";
FO_TAG_STEALTHVILE = "Arch-vile Sigiloso";
FO_TAG_STEALTHBARON = "Barón del Infierno Sigiloso";
FO_TAG_STEALTHCACO = "Cacodemonio Sigiloso";
FO_TAG_STEALTHCHAINGUY = "Ametrallador Sigiloso";
FO_TAG_STEALTHDEMON = "Demonio Toro Sigiloso";
FO_TAG_STEALTHKNIGHT = "Caballero del Infierno Sigiloso";
FO_TAG_STEALTHIMP = "Imp Sigiloso";
FO_TAG_STEALTHFATSO = "Mancubo Sigiloso";
FO_TAG_STEALTHUNDEAD = "Revenant Sigiloso";
FO_TAG_STEALTHSHOTGUY = "Sargento Sigiloso";
FO_TAG_STEALTHZOMBIE = "Zombie Sigiloso";

FO_TAG_ZOMBIEMAN = "Antiguo Humano";
FO_TAG_SHOTGUNGUY = "Antiguo Sargento";
FO_TAG_SSGGUY = "Antiguo Teniente";
FO_TAG_COMMANDO = "Antiguo Comando";
FO_TAG_PLASMAGUY = "Antiguo Coronel";
FO_TAG_BFGGUY = "Antiguo General";
FO_TAG_ZOMBIEMARINE = "Antiguo Marine";
FO_TAG_HUSK = "Zombie Cascarón";
FO_TAG_IMP = "Imp";
FO_TAG_IMP_NIGHTMARE = "Imp Pesadilla";
FO_TAG_IMPALER = "Empalador";
FO_TAG_HARVESTER = "Cosechador de Almas";
FO_TAG_PINKY = "Demonio Toro";
FO_TAG_SPECTRE = "Espectro";
FO_TAG_SPECTRE_NIGHTMARE = "Espectro Pesadilla";
FO_TAG_WRAITH = "Espectro Voraz";
FO_TAG_BUTCHER = "Carnicero";
FO_TAG_HOUND = "Sabueso del Infierno";
FO_TAG_ACID = "Demonio Ácido";
FO_TAG_SPIDER = "Aracnotrón";
FO_TAG_NIGHTCRAWLER = "Merodeador Nocturno";
FO_TAG_FATSO = "Mancubo";
FO_TAG_REVENANT = "Revenant";
FO_TAG_KNIGHT = "Caballero del Infierno";
FO_TAG_KNIGHTMARE = "Knightmare";
FO_TAG_BARON = "Barón del Infierno";
FO_TAG_BRUISER = "Bruiser";
FO_TAG_BELPHEGOR = "Belfegor";
FO_TAG_FALLEN = "Caído";
FO_TAG_CACO = "Cacodemonio";
FO_TAG_CACO_NIGHTMARE = "Cacodemonio Pesadilla";
FO_TAG_ELEMENTAL = "Elemental de Dolor";
FO_TAG_ELEMENTAL_NIGHTMARE = "Elemental de Agonía";
FO_TAG_PEST = "Pestilencia";
FO_TAG_LOSTSOUL = "Alma Perdida";
FO_TAG_STALKER = "Acechador";
FO_TAG_TRITE = "Trite";
FO_TAG_FORGOTTEN = "Olvidado";
FO_TAG_VILE = "Arch-vile";
FO_TAG_RESURRECTOR = "Resucitador Infernal";
FO_TAG_HELLSTORM = "Tormenta del Infierno";
FO_TAG_FLESH = "Mago de Carne";
FO_TAG_MOTHER = "Madre Demonio";
FO_TAG_CYBERDEMON = "Ciberdemonio";
FO_TAG_ANNIHILATOR = "Aniquilador";
FO_TAG_MASTERMIND = "Cerebro Arácnido Maestro";
FO_TAG_ERADICATOR = "Erradicador";
FO_TAG_WOLF3DSS = "Waffen-SS";
FO_TAG_CARRION = "Zombie Carroñero";
FO_TAG_THING = "La Cosa";
FO_TAG_EVILSPIRIT = "Poltergeist";
FO_TAG_VENOMEYE = "Ojo Venenoso";
FO_TAG_EVILTREE = "Árbol Maligno";
FO_TAG_EVILTREEROOT = "Raíz de Árbol Maligno";
FO_TAG_HANGMAN = "Ahorcado";
FO_TAG_KEEN = "Escorpión Ahorcado";
FO_TAG_SUPERFALLEN = "Caído Supremo";
FO_TAG_GORENEST = "Nido de Sangre";
FO_TAG_VASSAGO = "Vassago";

//////////////////////////////////////////////////////////////////
//NPC marine tags & obituary

FO_TAG_NPC_RIFLE = "Marine-Rifle";
FO_TAG_NPC_BFG = "Marine-BFG 9k";
FO_TAG_NPC_BERSERK = "Marine-Berserk";
FO_TAG_NPC_CHAINGUN = "Marine-Ametralladora";
FO_TAG_NPC_CHAINSAW = "Marine-Motosierra";
FO_TAG_NPC_FIST = "Marine-Desarmado";
FO_TAG_NPC_PLASMA = "Marine-Plasma";
FO_TAG_NPC_RAILGUN = "Marine-Gauss";
FO_TAG_NPC_ROCKET = "Marine-Cohete";
FO_TAG_NPC_SSG = "Marine-SúperEscopeta";
FO_TAG_NPC_SHOTGUN = "Marine-Escopeta";
FO_TAG_NPC_UNMAKE0 = "Marine-Deshacedor NV0";
FO_TAG_NPC_UNMAKE1 = "Marine-Deshacedor NV1";
FO_TAG_NPC_UNMAKE2 = "Marine-Deshacedor NV2";
FO_TAG_NPC_UNMAKE3 = "Marine-Deshacedor NV3";

FO_OB_NPC = "%o fue asesinado por fuego amigo. ¡Maldito seas!";

//////////////////////////////////////////////////////////////////
//monster obituaries

FO_OB_STEALTHBABY = "%o creyó ver un aracnotrón.";
FO_OB_STEALTHVILE = "%o creyó ver un arch-vile.";
FO_OB_STEALTHBARON = "%o creyó ver un Barón del Infierno.";
FO_OB_STEALTHCACO = "%o creyó ver un cacodemonio.";
FO_OB_STEALTHCHAINGUY = "%o creyó ver un ametrallador.";
FO_OB_STEALTHDEMON = "%o creyó ver un demonio toro.";
FO_OB_STEALTHKNIGHT = "%o creyó ver un Caballero del Infierno.";
FO_OB_STEALTHIMP = "%o creyó ver un imp.";
FO_OB_STEALTHFATSO = "%o creyó ver un mancubo.";
FO_OB_STEALTHUNDEAD = "%o creyó ver un revenant.";
FO_OB_STEALTHSHOTGUY = "%o creyó ver un sargento.";
FO_OB_STEALTHZOMBIE = "%o creyó ver un zombie.";

FO_OB_DEMONHIT = "%o fue mordido por un demonio toro.";
FO_OB_SPECTREHIT = "%o fue devorado por un espectro.";
FO_OB_SPECTREHIT_NIGHTMARE = "%o fue cazado por un espectro pesadilla.";
FO_OB_WRAITH = "%o fue rebanado por un espectro voraz.";
FO_OB_BUTCHER = "%o fue destripado por un carnicero.";
FO_OB_HOUND = "%o fue achicharrado por un sabueso del infierno.";
FO_OB_HOUNDHIT = "%o ahora es comida para perros.";
FO_OB_ACID = "%o fue disuelto por un demonio ácido.";
FO_OB_ACIDHIT = "%o fue despedazado por un demonio ácido.";
FO_OB_ZOMBIE = "%o fue asesinado por un zombie.";
FO_OB_ZOMBIEMARINE = "%o fue asesinado por un marine zombie.";
FO_OB_SHOTGUY = "%o fue disparado por un sargento.";
FO_OB_SSGGUY = "%o fue destrozado por un zombie con súper escopeta.";
FO_OB_PLASMAGUY = "%o fue derretido por un coronel zombie.";
FO_OB_BFGGUY = "%o fue iluminado por una ráfaga de BFG.";
FO_OB_HUSK = "La horda consumió a %o.";
FO_OB_VILE = "%o fue incinerado por un arch-vile.";
FO_OB_RESURRECTOR = "%o encontró la condenación eterna a manos del resucitador infernal.";
FO_OB_HELLSTORM = "%o fue despedazado por una tormenta del infierno.";
FO_OB_FLESH = "A %o un mago de carne le hirvió la sangre.";
FO_OB_UNDEAD = "%o no pudo esquivar la bola de fuego de un revenant.";
FO_OB_UNDEADHIT = "%o fue golpeado por un revenant.";
FO_OB_FATSO = "%o fue aplastado por un mancubo.";
FO_OB_CHAINGUY = "%o fue perforado por un ametrallador.";
FO_OB_SKULL = "%o fue asustado por un alma perdida.";
FO_OB_STALKER = "%o no vio venir al acechador.";
FO_OB_TRITE = "%o fue envenenado por un trite.";
FO_OB_FORGOTTEN = "%o fue electrocutado por un olvidado.";
FO_OB_IMP = "%o fue quemado por un imp.";
FO_OB_IMPHIT = "%o fue desgarrado por un imp.";
FO_OB_IMP_NIGHTMARE = "%o fue quemado por un imp pesadilla.";
FO_OB_IMPHIT_NIGHTMARE = "%o fue desgarrado por un imp pesadilla.";
FO_OB_IMPALER = "%o fue perforado por un empalador.";
FO_OB_IMPALERHIT = "%o fue empalado por un empalador.";
FO_OB_HARVESTER = "%o fue drenado por un cosechador de almas.";
FO_OB_CACO = "%o fue fulminado por un cacodemonio.";
FO_OB_CACOHIT = "%o se acercó demasiado a un cacodemonio.";
FO_OB_CACO_NIGHTMARE = "%o fue calcinado por un cacodemonio pesadilla.";
FO_OB_CACOHIT_NIGHTMARE = "%o fue masticado por un cacodemonio pesadilla.";
FO_OB_FALLEN = "%o fue inmolado por un caído.";
FO_OB_ELEMENTAL = "%o se acercó demasiado a un elemental de dolor.";
FO_OB_ELEMENTAL_NIGHTMARE = "%o fue atormentado por un elemental de agonía.";
FO_OB_PEST = "%o cayó ante la guerra química de Pestilencia.";
FO_OB_PESTHIT = "%o murió por los puños venenosos de Pestilencia.";
FO_OB_BARON = "%o fue golpeado por un Barón del Infierno.";
FO_OB_BARONHIT = "%o fue desgarrado por un Barón del Infierno.";
FO_OB_KNIGHT = "%o fue destrozado por un Caballero del Infierno.";
FO_OB_KNIGHTHIT = "%o fue destripado por un Caballero del Infierno.";
FO_OB_KNIGHTMARE = "%o fue calcinado por un knightmare.";
FO_OB_KNIGHTMAREHIT = "%o fue despedazado por un knightmare.";
FO_OB_BRUISER = "%o fue pulverizado por un bruiser.";
FO_OB_BELPHEGOR = "%o fue obliterado por un belfegor.";
FO_OB_SPIDER = "%o quedó atónito ante la Araña Maestra.";
FO_OB_SPIDERHIT = "%o fue aplastado bajo sus patas.";
FO_OB_ERADICATOR = "El Erradicador deshizo a %o.";
FO_OB_MOTHER = "%o fue obliterado por la Madre Demonio.";
FO_OB_BABY = "%o dejó que un aracnotrón lo vaporizara.";
FO_OB_NIGHTCRAWLER = "%o fue volado por un merodeador nocturno.";
FO_OB_CYBORG = "%o fue destrozado por un ciberdemonio.";
FO_OB_ANNIHILATOR = "El Aniquilador voló a %o en pedazos con sus cohetes.";
FO_OB_WOLFSS = "%o conoció a un Nazi.";
FO_OB_GHOST = "%o fue asesinado por un poltergeist.";
FO_OB_CARRION = "La horda infectó a %o.";
FO_OB_THING = "%o fue invertido por La Cosa.";
FO_OB_EVILEYE = "%o miró un Ojo Maligno por demasiado tiempo...";
FO_OB_EVILTREE = "%o fue empalado por un Árbol Maligno.";
FO_OB_HANGMAN = "%o fue emboscado por un ahorcado.";
FO_OB_SUPERFALLEN = "%o fue inmolado por un Caído Supremo.";
FO_OB_VASSAGO = "%o fue achicharrado por un Vassago.";

//////////////////////////////////////////////////////////////////
//prop Tags

FO_TAG_EXPLOSIVEBARREL = "Barril explosivo";
FO_TAG_THROWNBARREL = "¡Barril particularmente volátil!";

//////////////////////////////////////////////////////////////////
//locks for final BD64 map

FO_LOCK_ORANGE = "No tienes la capacidad para activarlo...";
FO_LOCK_PURPLE = "No tienes la capacidad para activarlo...";
FO_LOCK_BLUE = "No tienes la capacidad para activarlo...";