[es esm]

//OTHER SYSTEM STUFF
FO_64SYSTEM_APPLIED = "Aplicar cambios";

//////////////////////////////////////////////////////////////////
//menus

FO_MNU_64OPTIONS ="BD64 OPCIONES";

FO_MNU_CLASS = "Elige tu estilo de juego:";

FO_64OPTIONS_MAIN = "BRUTAL DOOM 64 OPCIONES";

FO_64OPTIONS_MAIN_TXT1 = "Algunos cambios no se inicializan automáticamente";
FO_64OPTIONS_MAIN_TXT2 = "Presione \"Aplicar cambios\" para que los cambios surtan efecto";

//////////////////////////////////////////////////////////////////
//ammo & misc item pickups
BD64_GOTMINES = "Recogiste un Explosive Mina!";

//////////////////////////////////////////////////////////////////
//weapon, item &  misc messages

WM_NOSTAMINA = "Sin Energias!";
WM_NOMINES = "Sin Minas en el inventario!";	

//////////////////////////////////////////////////////////////////
//Tags for Classes

FO_TAG_CLASS_CLASSIC = "Clasico";
FO_TAG_MODERN = "Moderno";
FO_TAG_CLASS_TACTICAL = "Tactico";

//////////////////////////////////////////////////////////////////
//Tags for Dificulties

FO_TAG_BABY = "Se Gentil!";
FO_TAG_BABY_TXT = "Equivale a 'I'm too young to die' (factor de munición x2)";
FO_TAG_EASY = "Dale, sin miedo!";
FO_TAG_EASY_TXT = "Equivale a 'Hey, not too rough'";
FO_TAG_NORMAL = "Prepara el culo!";
FO_TAG_NORMAL_TXT = "Equivale a 'Hurt me plenty'";
FO_TAG_HARD = "A ver si aguantas verme caer!";
FO_TAG_HARD_TXT = "Equivale a 'Ultra violence'";
FO_TAG_HARDER = "A ver si aguantas verme caer+!";
FO_TAG_HARDER_TXT = "Equivale a 'Ultra violence+', Projectiles enemigos acelerados, (solo para GZDoom) aparicion de armas del multijugador";
FO_TAG_NIGHTMARE = "DOLOR DE HUEVOS!";
FO_TAG_NIGHTMARE_TXT = "Monstruos con habilidades = Projectiles enemigos acelerados, +25% de vida y mas agrecivos";
FO_TAG_SURVIVAL = "SUPERVIVENCIA!";
FO_TAG_SURVIVAL_TXT = "Monstruos con habilidades = +25% de vida (Curacion manual).";
FO_TAG_REALISM = "SUPERVIVENCIA! (realista)";
FO_TAG_REALISM_TXT = "Monstruos con habilidades = Projectiles enemigos acelerados, -70% de vida, se inflinge el x5 de daño (Curacion manual)";

//////////////////////////////////////////////////////////////////
//Health / armor

FO_GOTARMBONUS = "Agarraste Armadura Extra.";
FO_GOTARMOR = "Agarraste una armadura.";
FO_GOTMEGA = "Agarraste una Mega armadura!";

FO_GOTHTHBONUS = "Agarraste una Vida Extra.";
FO_GOTSTIM = "Agarraste un paquete de estimulantes.";
FO_GOTMEDINEED = "Agarraste una medikit REALMENTE lo Necesitabas!";
FO_GOTMEDIKIT = "Agarraste una medikit.";

//////////////////////////////////////////////////////////////////
//powerups

FO_GOTINVUL = "Invulnerabilidad!";
FO_GOTSUPER = "SuperCarga!";
FO_GOTMSPHERE = "Mega Esfera!";
FO_GOTINVIS = "Invisibilidad Parcial!";
FO_GOTSUIT = "Proteccion Anti Radiacion!";
FO_GOTVISOR = "Lentes de Vision Nocturna!";
FO_GOTMAP = "Computadora GPS!";
FO_GOTBERSERK = "Berserk!";

//////////////////////////////////////////////////////////////////
//Keys

FO_GOTBLUECARD = "Agarraste una Tarjeta Azul.";
FO_GOTYELWCARD = "Agarraste una Tarjeta Amarilla.";
FO_GOTREDCARD = "Agarraste una Tarjeta Roja.";
FO_GOTBLUESKUL = "Agarraste una Calabera Azul.";
FO_GOTYELWSKUL = "Agarraste una Calabera Amarilla.";
FO_GOTREDSKUL = "Agarraste una Calabera Roja.";

//////////////////////////////////////////////////////////////////
//ammo

FO_GOTBACKPACK = "Agarraste una Mochila!";
FO_GOTCLIP = "Agarraste un Cargador.";
FO_GOTCLIPBOX = "Agarraste una Caja de balas.";
FO_GOTSHELLS = "Agarraste 4 Cartuchos.";
FO_GOTSHELLBOX = "Agarraste una Caja de Cartuchos.";
FO_GOTROCKET = "Agarraste un Coete.";
FO_GOTROCKBOX = "Agarraste una Caja Coete.";
FO_GOTCELL = "Agarraste una celda de energia.";
FO_GOTCELLBOX = "Agarraste un paquete de energia.";

//////////////////////////////////////////////////////////////////
//doors

/*
	PD_BLUEO = "You need a blue key.";
	PD_REDO = "You need a red key.";
	PD_YELLOWO = "You need a yellow key.";
	PD_BLUEK = "You need a blue key.";
	PD_REDK = "You need a red key.";
	PD_YELLOWK = "You need a yellow key.";
	PD_BLUEC = "You need a blue key card.";
	PD_REDC = "You need a red key card.";
	PD_YELLOWC = "You need a yellow key card.";
	PD_BLUECO = "You need a blue key card.";
	PD_REDCO = "You need a red key card.";
	PD_YELLOWCO = "You need a yellow key card.";
	PD_BLUESO = "You need a blue skull key.";
	PD_REDSO = "You need a red skull key.";
	PD_YELLOWSO = "You need a yellow skull key.";
	PD_BLUES = "You need a blue skull key.";
	PD_REDS = "You need a red skull key.";
	PD_YELLOWS = "You need a yellow skull key.";
	PD_ANY = "You need a key.";
	PD_All3 = "You need all three keys.";
	PD_All6 = "You need all six keys.";
*/

//////////////////////////////////////////////////////////////////
//weapon pickups

//Slot 1
BD64_GOTCHAINSAW = "Una motocierra! A buscar presas! (Slot 1)";
//Slot 2
BD64_GOTPISTOL = "Recogiste una pistola! (Slot 2)";
BD64_GOTSMG = "Recogiste una Sub Ametralladora! (Slot 2)";
BD64_GOTMP40 = "Recogiste una MP40! (Slot 2)";
//Slot 3
BD64_GOTSHOTGUN = "Recogiste una Escopeta! (Slot 3)";
BD64_GOTSHOTGUN2 = "Recogiste una Super Escopeta! (Slot 3)";
//Slot 4
BD64_GOTRIFLE = "Recogiste un Rifle de asalto! (Slot 4)";
BD64_GOTCHAINGUN = "Recogiste una Gambling! (Slot 4)";
//Slot 5
BD64_GOTLAUNCHER = "Recogiste un Lanza Coetes! (Slot 5)";
//Slot 6
BD64_GOTPLASMA = "Recogiste un Rifle de Plasma! (Slot 6)";
BD64_GOTGAUSS = "Recogiste una 'Gauss Cannon!' (Slot 6)";
//Slot 7
BD64_GOTBFG9000 = "Recogiste una BFG9000! Oh, me vengo. (Slot 7)";
//Slot 8
BD64_GOTUNMAKER = "QUE 58#$%& ES ESTO! (Slot 8)";
//Slot 9
BD64_GOTLASER = "Recogiste un Rifle Laser! (Slot 9)";

//////////////////////////////////////////////////////////////////
// weapon tags

//1
FO_TAG_FIST = "Corta y Desgarra";
FO_TAG_CHAINSAW = "Motocierra";
FO_TAG_PORTMEDIKIT = "primeros auxilios";
//2
FO_TAG_PISTOL = "Pistola";
//3
FO_TAG_SHOTGUN = "Escopeta";
FO_TAG_SUPERSHOTGUN = "Super Escopeta";
//4
FO_TAG_CHAINGUN = "Gambling";
//5
FO_TAG_ROCKETLAUNCHER = "Lanza Coetes";
//6
FO_TAG_PLASMARIFLE = "Rifle de Plasma";
//7
FO_TAG_BFG9000 = "BFG9000";

//////////////////////////////////////////////////////////////////
//obituaries for weapons

FO_OB_MPFIST = "%o chewed on %k's fist.";
FO_OB_MPCHAINSAW = "%o was mowed over by %k's chainsaw.";
FO_OB_MPPISTOL = "%o was tickled by %k's pea shooter.";
FO_OB_MPSHOTGUN = "%o chewed on %k's boomstick.";
FO_OB_MPSSHOTGUN = "%o was splattered by %k's super shotgun.";
FO_OB_MPCHAINGUN = "%o was mowed down by %k's chaingun.";
FO_OB_MPROCKET = "%o rode %k's rocket.";
//	OB_MPR_SPLASH = "%o almost dodged %k's rocket.";
FO_OB_MPPLASMARIFLE = "%o was melted by %k's plasma gun.";
FO_OB_MPBFG_BOOM = "%o was splintered by %k's BFG.";
//	OB_MPBFG_SPLASH = "%o couldn't hide from %k's BFG.";
//	OB_MPTELEFRAG = "%o was telefragged by %k.";
//	OB_RAILGUN = "%o was railed by %k.";
//	OB_MPBFG_MBF = "%o was burned by %k's BFG.";

//////////////////////////////////////////////////////////////////
//obituaries for Demons

FO_OB_STEALTHBABY = "%o thought %g saw an arachnotron.";
FO_OB_STEALTHVILE = "%o thought %g saw an archvile.";
FO_OB_STEALTHBARON = "%o thought %g saw a Baron of Hell.";
FO_OB_STEALTHCACO = "%o thought %g saw a cacodemon.";
FO_OB_STEALTHCHAINGUY = "%o thought %g saw a chaingunner.";
FO_OB_STEALTHDEMON = "%o thought %g saw a demon.";
FO_OB_STEALTHKNIGHT = "%o thought %g saw a Hell Knight.";
FO_OB_STEALTHIMP = "%o thought %g saw an imp.";
FO_OB_STEALTHFATSO = "%o thought %g saw a mancubus.";
FO_OB_STEALTHUNDEAD = "%o thought %g saw a revenant.";
FO_OB_STEALTHSHOTGUY = "%o thought %g saw a sergeant.";
FO_OB_STEALTHZOMBIE = "%o thought %g saw a zombieman.";

FO_OB_UNDEADHIT = "%o fue golpeado por un Revenant.";
FO_OB_IMPHIT = "%o fue desmembrado por un imp.";
FO_OB_CACOHIT = "%o fue comido por un cacodemon.";
FO_OB_DEMONHIT = "%o fue mordido por un Pinky.";
FO_OB_SPECTREHIT = "%o fue devorado por un espectro.";
FO_OB_BARONHIT = "%o fue desgarrado por un Barón del Infierno.";
FO_OB_KNIGHTHIT = "%o fue destripado por un Caballero del Infierno.";
FO_OB_ZOMBIE = "%o fue acribillado por un muerto viviente.";
FO_OB_SHOTGUY = "%o fue fusilado por un sargento.";
FO_OB_VILE = "%o fue incinerado por un archvile.";
FO_OB_UNDEAD = "%o no pudo evadir el misil de un revenant.";
FO_OB_FATSO = "%o fue reventado en mil pedazos por un mancubus.";
FO_OB_CHAINGUY = "%o fue brutalmente perforado por un artillero.";
FO_OB_SKULL = "%o fue quemado por un alma en pena.";
FO_OB_IMP = "%o fue Incenerado por un imp.";
FO_OB_CACO = "%o fue incinerado por un cacodemon.";
FO_OB_BARON = "%o fue destrozado/reventado por un Barón del Infierno.";
FO_OB_KNIGHT = "%o fue magullado por un Caballero del Infierno.";
FO_OB_SPIDER = "%o se quedó atónito ante la Araña Maestra.";
FO_OB_BABY = "%o dejó que un aracnotrón se llevara a %h.";
FO_OB_CYBORG = "%o fue destrozado por un ciberdemonio.";
FO_OB_WOLFSS = "%o conoció a un Nazi.";
//	OB_DOG = "%o was mauled by a dog.";