#define MAXPLAYERS 8
int flashlightOn[MAXPLAYERS];

Script "ToggleFlashlight" (void)
{
    if (flashlightOn[PlayerNumber()])
        flashlightOn[PlayerNumber()] = 0;
    else
        flashlightOn[PlayerNumber()] = 1;
        
    if (CheckInventory("FlashLightPickup") == 0)
    {
        Delay(1);
        flashlightOn[PlayerNumber()] = 0;
        terminate;
    }
    ActivatorSound("flashlight/click", 127);
}

Script "FlashlightHandling" ENTER
{
    While(1)
    {
        if (flashlightOn[PlayerNumber()])
        {
            GiveInventory("FlashlightSpawner",1);
        }
        Delay(1);
    }
}

Script "FlashLightStartACS" OPEN 
{
    if (GetCvar("FlashlightStartCvar") == 1)
    {
        for (int i = 0; i < MAXPLAYERS; i++)
        {
            if (PlayerInGame(i))
            {
                SetActivatorToPlayer(i);
                GiveInventory("FlashlightPickup",1);
            }
        }
    }
}