#library "BD64ACS"
#import "zcommon.bcs"
//#include "ACSFunc.acs"
#include "BCSFunc.acs"
#include "BD64FlashlightACS.acs"
#include "BD64ScreenFXACS.acs"
#include "BD64Inputs.acs"
#include "BD64Spawners.acs"
#include "BD64Preset.acs"
#include "BD64MapDetect.acs"

script "BD64Respawn" Respawn NET
{
	SetInventory("HudSwitch",getusercvar(PlayerNumber(),"HUDSwitchCvar")); //Hud to Doom Style
	SetInventory("NoReloading",getcvar("NoReloadCvar")); //Reloading Mode
	SetInventory("VWeaponMode",getCvar("VWeaponCvar")); //Classic Weapons mode for Classical Mode
	SetInventory("AltLaserSkin",getuserCvar(PlayerNumber(),"AlternativeLaserSkinCvar")); //Alternative Lasergun skins

	//Classic Weapons Mode for Tactical and Modern Classes
	SetInventory("ClassicRLToken",getcvar("ClassicRLCvar"));
	SetInventory("ClassicChaingunToken",getcvar("ClassicChaingunCvar"));
	SetInventory("ClassicChainsawToken",getcvar("VanillaChainsawCvar"));

	Delay(1);
}

#libdefine SKILL_SURVIVAL 6
#libdefine SKILL_SURVIVAL_REALISM 7
#libdefine SKILL_HARD_PLUS 33

Script "BD64Initilize" Enter
{
	if(GameType() == GAME_TITLE_MAP) terminate;

	if(GameType () == GAME_SINGLE_PLAYER)
	{
		sethudsize(160,90,TRUE);
		setfont("BLASCR");
		HudMessageBold(s:"a"; HUDMSG_FADEOUT,1,CR_BLACK,0.1,0.1,0.1,1.0);
	}

	ACS_NamedExecuteAlways("BD64Respawn",0);
	CreateTranslation(2666,0:255=%[0,0,0]:[0.94,0.97,1.00]);//ALICE BLUE

	int pc = GetPlayerInfo(PlayerNumber(),PLAYERINFO_PLAYERCLASS);
	if (pc == 1 || pc == 2)
	{

	}
	else
	{
		TakeInventory("Stamina",100);
	}

	if(GetCvar("WeaponsWarmUpCvar") == 0) //First Select Animation
	{
		TakeInventory("StartWeapon",1);
		TakeInventory("NeverSelectedPistol",1);
		TakeInventory("NeverSelectedRifle",1);
		TakeInventory("NeverSelectedShotgun",1);
		TakeInventory("NeverSelectedSSG",1);
		TakeInventory("NeverSelectedSMG",1);
		TakeInventory("NeverSelectedRL",1);
		TakeInventory("NeverSelectedPlasma",1);
		TakeInventory("NeverSelectedGauss",1);
	}

	//Watch Me Die+ (Zandronum emulation)
	if(GameSkill() == SKILL_HARD_PLUS && IsZandronum())
	{
		if(GameType() == GAME_NET_COOPERATIVE) terminate;
		else
		{
		ConsoleCommand("netgame 1");
		Log(l:"FO_TAG_HARDER_RELOAD_MESSAGE");
		ChangeLevel(StrParam(n:PRINTNAME_LEVEL),0,CHANGELEVEL_NOINTERMISSION,-1);
		}
	}	

	//Survival Mode
	if(GameSkill() == SKILL_SURVIVAL || GameSkill() == SKILL_SURVIVAL_REALISM)
	if(PlayerClass(PlayerNumber()) == 0)
		GiveInventory("64PortableFirstAidKit",1);
	else
	GiveInventory("64PortableFirstAidKitTACTICAL",1);

	//Map Checker
	SetInventory("VmapCheck",GetCvar("VMapCheckCvar")); //Vanilla Final Outpost and The Absolution
	SetInventory("TCMapCheck",GetCvar("TCMapCheckCvar"));
}

script "IceDeathTranslate" (void) NET
{
Thing_SetTranslation(0,2666);
Delay(1);
}

Script "PlayerDeathScript" Death
{
	Delay(1);
	TakeInventory("ClassicChainsawToken",1);
	TakeInventory("ClassicRLToken",1);
}

Script "DM_SpawnACS" (void)
{
if	(GameType() == GAME_NET_DEATHMATCH)
	GiveInventory("IsDM",1);
}

script "GoreCleanerACS" (void) NET CLIENTSIDE
{
    if (GameType() == GAME_NET_DEATHMATCH || GetUserCVar(ConsolePlayerNumber(),"GoreCleanerCvar") == 1)
    {
        SetResultValue(1);
    }
    else
    {
        SetResultValue(0);
    }
}

script "Zandro_Check" OPEN
{
if(IsZandronum())
	{
	ConsoleCommand("compat_clientssendfullbuttoninfo 1");
	}
}

script "HaloDisabledACS" (void) NET CLIENTSIDE
{
    int mode = GetUserCVar(ConsolePlayerNumber(),"LightFogCvar");
    SetResultValue(mode == 1 || mode == 2);
}

script "LightFogDisabledACS" (void) NET CLIENTSIDE
{
    int mode = GetUserCVar(ConsolePlayerNumber(),"LightFogCvar");
    SetResultValue(mode == 1 || mode == 3);
}

script "BerserkSwitchFistsACS" (void) NET
{
	if(GetUserCVar(PlayerNumber(),"BerserkSwitchFistsCvar") == true)	
	{
		If(CheckInventory("IsTacticalClass") || CheckInventory("IsModern"))
		{
			SetWeapon("64FistTactical");
		}	
		else
		{
			SetWeapon("64Fist");
		}
	}
}

script "SoulHandler" ENTER { Thing_ChangeTID(0,6666 + PlayerNumber()); }			//assigns player a TID on map start
script "SoulHandlerRespawn" RESPAWN { Thing_ChangeTID(0,6666 + PlayerNumber()); }	//reassigns player a TID after respawn

script "TUnmakerChecker" (void) NET
{
	int highestResult = 1;

	for (int p = 0; p < 64; p++)
	{
		if (!PlayerInGame(p)) continue;

		int tid = 6666 + p;

		if (CheckActorInventory(tid,"unmakerTACTICAL") || CheckActorInventory(tid,"64RuinerTACTICAL"))
		{
			int currentResult = 2;

			if ((CheckActorInventory(tid,"WpnPower1Icon") && CheckActorInventory(tid,"WpnPower2Icon") && CheckActorInventory(tid,"WpnPower3Icon"))
			|| CheckActorInventory(tid,"WpnPower4Icon") || CheckActorInventory(tid,"WpnPower5Icon"))
			{
				currentResult = 3;
			}

			if (currentResult > highestResult)
			{
				highestResult = currentResult;

				if (highestResult == 3) break;
			}
		}
	}
	SetResultValue(highestResult);
}

/*script "WeaponPickupChecker" (int Weapon)
{
	static str WeaponPickups[50] =
	{ //Regular Weapons
		"64Chainsaw","64Pistol","64SMG","64Shotgun","64SuperShotgun","64Chaingun","64Rifle","64RocketLauncher","64PlasmaRifle","64GaussCannon","64BFG9000","Unmaker","Lasergun","64MP40",
		//Xtra Weapons
		"64FireAxe","64Revolver","64AssaultShotgun","64QuadShotgun","64HexaShotgun","64LMG","64SniperRifle","64NadeLauncher","64Nailgun","64BFG10K","64Ruiner","64Flamethrower","64HeatseekerLauncher","64NuclearMissileLauncher"
		};


	If(CheckInventory("IsTacticalClass") || CheckInventory("IsModern"))
	{
		str TacticalWeaponPickup = StrParam(s:WeaponPickups[Weapon-1],s:"Tactical");
		
		GiveInventory(TacticalWeaponPickup,1);
		SetWeapon(TacticalWeaponPickup);
	}	
	else
	{
		GiveInventory(WeaponPickups[Weapon-1],1);
		SetWeapon(WeaponPickups[Weapon-1]);
	}
}*/

script "CensoredHealingACS"	(void) { SetResultValue(GetCVar("CensoredHealing_Cvar")); }
script "AltAmmoSpritesACS"	(void) { SetResultValue(GetCVar("AlternativeAmmoPickupSpritesCvar")); }
script "AlphaSpritesACS"	(void) { SetResultValue(GetCvar("AlphaPickupCvar")); }
script "ClassicTorchACS"	(void) { SetResultValue(GetCvar("ClassicTorchCvar")); }

script "LiquidSplashACS"	(void) NET CLIENTSIDE { SetResultValue(GetUserCVar(ConsolePlayerNumber(),"LiquidSplashCvar")); }
script "FlatDecalACS"		(void) NET CLIENTSIDE { SetResultValue(GetUserCVar(ConsolePlayerNumber(),"FlatDecalCvar")); }
script "SetBloodAmountACS"	(void) NET CLIENTSIDE { SetResultValue(GetUserCVar(ConsolePlayerNumber(),"SetBloodAmountCvar")); }
script "FootStepCheckACS"	(void) NET CLIENTSIDE { SetResultValue(GetUserCVar(ConsolePlayerNumber(),"FootStepCheckCvar")); }

script "LowAmmoSFXACS" (void) NET CLIENTSIDE
{
    if (GetUserCVar(PlayerNumber(),"LowAmmoSFXCvar") == 1) 
    { 
        PlaySound(0,"Weapon/LowAmmo",CHAN_AUTO,1.0,false,1.0,true); 
    }
}

script "RandomCvars" (void) NET
{
	SetCvar("Chaingun_Spawner_Cvar",0);
	SetCvar("PlasmaRifle_Spawner_Cvar",0);
	SetCvar("BFG_Spawner_Cvar",0);
//	SetCvar("WpnPower_Spawner_Cvar",0);
	SetCvar("BonusRandomCvar",0);
	SetCvar("Zombieman_Spawner_Cvar",0);
	SetCvar("Shotgunguy_Spawner_Cvar",random(-2,0));
	SetCvar("Chaingunguy_Spawner_Cvar",0);
	SetCvar("Imp_Spawner_Cvar",random(-2,0));
	SetCvar("Demon_Spawner_Cvar",random(-2,0));
	SetCvar("Spectre_Spawner_Cvar",random(-2,0));
	SetCvar("Cacodemon_Spawner_Cvar",random(-2,0));
	SetCvar("LostSoul_Spawner_Cvar",random(-2,0));
	SetCvar("Arachnotron_Spawner_Cvar",random(-2,0));
	SetCvar("HellKnight_Spawner_Cvar",random(-2,0));
	SetCvar("Revenant_Spawner_Cvar",0);
	SetCvar("Baron_Spawner_Cvar",random(-2,0));
	SetCvar("Fatso_Spawner_Cvar",0);
	SetCvar("PainElemental_Spawner_Cvar",0);
	SetCvar("Archvile_Spawner_Cvar",random(-2,0));
	SetCvar("Cyberdemon_Spawner_Cvar",random(-2,0));
	SetCvar("Mastermind_Spawner_Cvar",random(-2,0));
	SetCvar("TheHorde_Multiplier_Cvar",0);
	SetCvar("PoltergeistCvar",1);
	SetCvar("ThingRandomCvar",1);
	ACS_NamedExecuteAlways("RandomMonstersPercentACS",0);
	ACS_NamedExecuteAlways("BD64Respawn",0);
	delay(1);
}

script "RandomMonstersPercentACS" (void) NET
{
	SetCvar("bd64_SpawnPercentZombieman",random(1,10));
	SetCvar("bd64_SpawnPercentShotgunguy",random(1,10));
	SetCvar("bd64_SpawnPercentChaingunguy",random(1,10));
	SetCvar("bd64_SpawnPercentImp",random(1,10));
	SetCvar("bd64_SpawnPercentDemon",random(1,10));
	SetCvar("bd64_SpawnPercentSpectre",random(1,10));
	SetCvar("bd64_SpawnPercentCacodemon",random(1,10));
	SetCvar("bd64_SpawnPercentLostSoul",random(1,10));
	SetCvar("bd64_SpawnPercentPainElemental",random(1,10));
	SetCvar("bd64_SpawnPercentHellKnight",random(1,10));
	SetCvar("bd64_SpawnPercentBaron",random(1,10));
	SetCvar("bd64_SpawnPercentRevenant",random(1,10));
	SetCvar("bd64_SpawnPercentArachnotron",random(1,10));
	SetCvar("bd64_SpawnPercentMancubus",random(1,10));
	SetCvar("bd64_SpawnPercentCyberdemon",random(1,10));
	SetCvar("bd64_SpawnPercentMastermind",random(1,10));
	delay(1);
}