#define MAXPLAYERS 64
int flashlightOn[MAXPLAYERS];

Script "ToggleFlashlight" (void) NET
{
	if (GetActorProperty(0,APROP_HEALTH) <= 0)
		terminate;

	if (CheckInventory("FlashLightPickup") == 0)
	{
		Print(l:"NEED_FLASHLIGHT");
		flashlightOn[PlayerNumber()] = 0;
		terminate;
	}

	flashlightOn[PlayerNumber()] = !flashlightOn[PlayerNumber()];
	ActivatorSound("flashlight/click",127);
}

Script "FlashlightHandling" ENTER
{
	int pNum = PlayerNumber();

	while (1)
	{
		if (flashlightOn[pNum])
		{
			if (GetActorProperty(0,APROP_HEALTH) > 0 && CheckInventory("FlashLightPickup"))
			{
				GiveInventory("FlashlightSpawner",1);
			}
			else
			{
				flashlightOn[pNum] = 0;
			}
		}

		Delay(1);
	}
}