//Original addon for BDv21 by Mechanical-Sanity 
//Port to BD64 by IDDQD_1337

//Red Blood
script 580 (void) CLIENTSIDE
{
	if (GetCvar("bd64_ScreenFX") == 1)
	{
		SetHudSize(400,250,1);
		int id = 580;

		delay(1);
		setfont("RBLD1");  hudmessage(s:"A"; HUDMSG_PLAIN,id,CR_UNTRANSLATED,63.1,61.1,0.15);
		delay(4);
		setfont("RBLD2");  hudmessage(s:"A"; HUDMSG_PLAIN,id,CR_UNTRANSLATED,63.1,61.1,0.15);
		delay(4);
		setfont("RBLD3");  hudmessage(s:"A"; HUDMSG_PLAIN,id,CR_UNTRANSLATED,63.1,61.1,0.15);
		delay(4);
		setfont("RBLD4");  hudmessage(s:"A"; HUDMSG_PLAIN,id,CR_UNTRANSLATED,63.1,61.1,0.15);
		delay(4);
		setfont("RBLD5");  hudmessage(s:"A"; HUDMSG_PLAIN,id,CR_UNTRANSLATED,63.1,61.1,0.15);
		delay(4);
		setfont("RBLD6");  hudmessage(s:"A"; HUDMSG_PLAIN,id,CR_UNTRANSLATED,63.1,61.1,0.15);
		delay(4);
		setfont("RBLD7");  hudmessage(s:"A"; HUDMSG_PLAIN,id,CR_UNTRANSLATED,63.9,61.9,0.15);
		delay(4);
		setfont("RBLD8");  hudmessage(s:"A"; HUDMSG_PLAIN,id,CR_UNTRANSLATED,63.9,61.9,0.15);
		delay(4);
		setfont("RBLD9");  hudmessage(s:"A"; HUDMSG_PLAIN,id,CR_UNTRANSLATED,63.9,61.9,0.15);
		delay(4);
		setfont("RBLD10"); hudmessage(s:"A"; HUDMSG_PLAIN,id,CR_UNTRANSLATED,63.9,61.9,0.15);
		delay(4);
		setfont("RBLD11"); hudmessage(s:"A"; HUDMSG_PLAIN,id,CR_UNTRANSLATED,63.9,61.9,0.15);
		delay(4);
	}
	if (GetCvar("bd64_ScreenFX") == 2)
	{
		ACS_Execute(680,0,0,0,0);
	}
}

script 581 (void) CLIENTSIDE
{
	if (GetCvar("bd64_ScreenFX") == 1)
	{
		SetHudSize(400,250,1);
		int id = 581;

		delay(2);
		setfont("RBLD1");  hudmessage(s:"A"; HUDMSG_PLAIN,id,CR_UNTRANSLATED,0.9,30.9,0.15);
		delay(4);
		setfont("RBLD2");  hudmessage(s:"A"; HUDMSG_PLAIN,id,CR_UNTRANSLATED,0.9,30.9,0.15);
		delay(4);
		setfont("RBLD3");  hudmessage(s:"A"; HUDMSG_PLAIN,id,CR_UNTRANSLATED,0.9,30.9,0.15);
		delay(4);
		setfont("RBLD4");  hudmessage(s:"A"; HUDMSG_PLAIN,id,CR_UNTRANSLATED,0.9,30.9,0.15);
		delay(4);
		setfont("RBLD5");  hudmessage(s:"A"; HUDMSG_PLAIN,id,CR_UNTRANSLATED,0.9,30.9,0.15);
		delay(4);
		setfont("RBLD6");  hudmessage(s:"A"; HUDMSG_PLAIN,id,CR_UNTRANSLATED,0.9,30.9,0.15);
		delay(4);
		setfont("RBLD7");  hudmessage(s:"A"; HUDMSG_PLAIN,id,CR_UNTRANSLATED,0.9,30.9,0.15);
		delay(4);
		setfont("RBLD8");  hudmessage(s:"A"; HUDMSG_PLAIN,id,CR_UNTRANSLATED,0.9,30.9,0.15);
		delay(4);
		setfont("RBLD9");  hudmessage(s:"A"; HUDMSG_PLAIN,id,CR_UNTRANSLATED,0.9,30.9,0.15);
		delay(4);
		setfont("RBLD10"); hudmessage(s:"A"; HUDMSG_PLAIN,id,CR_UNTRANSLATED,0.9,30.9,0.15);
		delay(4);
		setfont("RBLD11"); hudmessage(s:"A"; HUDMSG_PLAIN,id,CR_UNTRANSLATED,0.9,30.9,0.15);
		delay(4);
	}
	if (GetCvar("bd64_ScreenFX") == 2)
	{
		ACS_Execute(681,0,0,0,0);
	}
}

script 582 (void) CLIENTSIDE
{
	if (GetCvar("bd64_ScreenFX") == 1)
	{
		SetHudSize(400,250,1);
		int id = 582;

		delay(3);
		setfont("RBLD1");  hudmessage(s:"A"; HUDMSG_PLAIN,id,CR_UNTRANSLATED,263.1,81.1,0.15);
		delay(4);
		setfont("RBLD2");  hudmessage(s:"A"; HUDMSG_PLAIN,id,CR_UNTRANSLATED,263.1,81.1,0.15);
		delay(4);
		setfont("RBLD3");  hudmessage(s:"A"; HUDMSG_PLAIN,id,CR_UNTRANSLATED,263.1,81.1,0.15);
		delay(4);
		setfont("RBLD4");  hudmessage(s:"A"; HUDMSG_PLAIN,id,CR_UNTRANSLATED,263.1,81.1,0.15);
		delay(4);
		setfont("RBLD5");  hudmessage(s:"A"; HUDMSG_PLAIN,id,CR_UNTRANSLATED,263.1,81.1,0.15);
		delay(4);
		setfont("RBLD6");  hudmessage(s:"A"; HUDMSG_PLAIN,id,CR_UNTRANSLATED,263.1,81.1,0.15);
		delay(4);
		setfont("RBLD7");  hudmessage(s:"A"; HUDMSG_PLAIN,id,CR_UNTRANSLATED,263.9,81.9,0.15);
		delay(4);
		setfont("RBLD8");  hudmessage(s:"A"; HUDMSG_PLAIN,id,CR_UNTRANSLATED,263.9,81.9,0.15);
		delay(4);
		setfont("RBLD9");  hudmessage(s:"A"; HUDMSG_PLAIN,id,CR_UNTRANSLATED,263.9,81.9,0.15);
		delay(4);
		setfont("RBLD10"); hudmessage(s:"A"; HUDMSG_PLAIN,id,CR_UNTRANSLATED,263.9,81.9,0.15);
		delay(4);
		setfont("RBLD11"); hudmessage(s:"A"; HUDMSG_PLAIN,id,CR_UNTRANSLATED,263.9,81.9,0.15);
		delay(4);
	}
}

script 583 (void) CLIENTSIDE
{
	if (GetCvar("bd64_ScreenFX") == 1)
	{
		SetHudSize(400,250,1);
		int id = 583;

		delay(4);
		setfont("RBLD1");  hudmessage(s:"A"; HUDMSG_PLAIN,id,CR_UNTRANSLATED,123.1,-11.1,0.15);
		delay(4);
		setfont("RBLD2");  hudmessage(s:"A"; HUDMSG_PLAIN,id,CR_UNTRANSLATED,123.1,-11.1,0.15);
		delay(4);
		setfont("RBLD3");  hudmessage(s:"A"; HUDMSG_PLAIN,id,CR_UNTRANSLATED,123.1,-11.1,0.15);
		delay(4);
		setfont("RBLD4");  hudmessage(s:"A"; HUDMSG_PLAIN,id,CR_UNTRANSLATED,123.1,-11.1,0.15);
		delay(4);
		setfont("RBLD5");  hudmessage(s:"A"; HUDMSG_PLAIN,id,CR_UNTRANSLATED,123.1,-11.1,0.15);
		delay(4);
		setfont("RBLD6");  hudmessage(s:"A"; HUDMSG_PLAIN,id,CR_UNTRANSLATED,123.1,-11.1,0.15);
		delay(4);
		setfont("RBLD7");  hudmessage(s:"A"; HUDMSG_PLAIN,id,CR_UNTRANSLATED,123.9,-11.9,0.15);
		delay(4);
		setfont("RBLD8");  hudmessage(s:"A"; HUDMSG_PLAIN,id,CR_UNTRANSLATED,123.9,-11.9,0.15);
		delay(4);
		setfont("RBLD9");  hudmessage(s:"A"; HUDMSG_PLAIN,id,CR_UNTRANSLATED,123.9,-11.9,0.15);
		delay(4);
		setfont("RBLD10"); hudmessage(s:"A"; HUDMSG_PLAIN,id,CR_UNTRANSLATED,123.9,-11.9,0.15);
		delay(4);
		setfont("RBLD11"); hudmessage(s:"A"; HUDMSG_PLAIN,id,CR_UNTRANSLATED,123.9,-11.9,0.15);
		delay(4);
	}
}

script 584 (void) CLIENTSIDE
{
	if (GetCvar("bd64_ScreenFX") == 1)
	{
		SetHudSize(400,250,1);
		int id = 584;

		delay(4);
		setfont("RBLD1");  hudmessage(s:"A"; HUDMSG_PLAIN,id,CR_UNTRANSLATED,213.1,101.1,0.15);
		delay(4);
		setfont("RBLD2");  hudmessage(s:"A"; HUDMSG_PLAIN,id,CR_UNTRANSLATED,213.1,101.1,0.15);
		delay(4);
		setfont("RBLD3");  hudmessage(s:"A"; HUDMSG_PLAIN,id,CR_UNTRANSLATED,213.1,101.1,0.15);
		delay(4);
		setfont("RBLD4");  hudmessage(s:"A"; HUDMSG_PLAIN,id,CR_UNTRANSLATED,213.1,101.1,0.15);
		delay(4);
		setfont("RBLD5");  hudmessage(s:"A"; HUDMSG_PLAIN,id,CR_UNTRANSLATED,213.1,101.1,0.15);
		delay(4);
		setfont("RBLD6");  hudmessage(s:"A"; HUDMSG_PLAIN,id,CR_UNTRANSLATED,213.1,101.1,0.15);
		delay(4);
		setfont("RBLD7");  hudmessage(s:"A"; HUDMSG_PLAIN,id,CR_UNTRANSLATED,213.9,101.9,0.15);
		delay(4);
		setfont("RBLD8");  hudmessage(s:"A"; HUDMSG_PLAIN,id,CR_UNTRANSLATED,213.9,101.9,0.15);
		delay(4);
		setfont("RBLD9");  hudmessage(s:"A"; HUDMSG_PLAIN,id,CR_UNTRANSLATED,213.9,101.9,0.15);
		delay(4);
		setfont("RBLD10"); hudmessage(s:"A"; HUDMSG_PLAIN,id,CR_UNTRANSLATED,213.9,101.9,0.15);
		delay(4);
		setfont("RBLD11"); hudmessage(s:"A"; HUDMSG_PLAIN,id,CR_UNTRANSLATED,213.9,101.9,0.15);
		delay(4);
	}
}

script 585 (void) CLIENTSIDE
{
	if (GetCvar("bd64_ScreenFX") == 1)
	{
		SetHudSize(400,250,1);
		int id = 585;

		delay(4);
		setfont("RBLD1");  hudmessage(s:"A"; HUDMSG_PLAIN,id,CR_UNTRANSLATED,213.1,11.1,0.15);
		delay(4);
		setfont("RBLD2");  hudmessage(s:"A"; HUDMSG_PLAIN,id,CR_UNTRANSLATED,213.1,11.1,0.15);
		delay(4);
		setfont("RBLD3");  hudmessage(s:"A"; HUDMSG_PLAIN,id,CR_UNTRANSLATED,213.1,11.1,0.15);
		delay(4);
		setfont("RBLD4");  hudmessage(s:"A"; HUDMSG_PLAIN,id,CR_UNTRANSLATED,213.1,11.1,0.15);
		delay(4);
		setfont("RBLD5");  hudmessage(s:"A"; HUDMSG_PLAIN,id,CR_UNTRANSLATED,213.1,11.1,0.15);
		delay(4);
		setfont("RBLD6");  hudmessage(s:"A"; HUDMSG_PLAIN,id,CR_UNTRANSLATED,213.1,11.1,0.15);
		delay(4);
		setfont("RBLD7");  hudmessage(s:"A"; HUDMSG_PLAIN,id,CR_UNTRANSLATED,213.9,11.9,0.15);
		delay(4);
		setfont("RBLD8");  hudmessage(s:"A"; HUDMSG_PLAIN,id,CR_UNTRANSLATED,213.9,11.9,0.15);
		delay(4);
		setfont("RBLD9");  hudmessage(s:"A"; HUDMSG_PLAIN,id,CR_UNTRANSLATED,213.9,11.9,0.15);
		delay(4);
		setfont("RBLD10"); hudmessage(s:"A"; HUDMSG_PLAIN,id,CR_UNTRANSLATED,213.9,11.9,0.15);
		delay(4);
		setfont("RBLD11"); hudmessage(s:"A"; HUDMSG_PLAIN,id,CR_UNTRANSLATED,213.9,11.9,0.15);
		delay(4);
	}
}

//Green Blood
script 560 (void) CLIENTSIDE
{
	if (GetCvar("bd64_ScreenFX") == 1)
	{
		SetHudSize(400,250,1);
		int id = 560;

		delay(1);
		setfont("GBLD1");  hudmessage(s:"A"; HUDMSG_PLAIN,id,CR_UNTRANSLATED,73.1,71.1,0.15);
		delay(4);
		setfont("GBLD2");  hudmessage(s:"A"; HUDMSG_PLAIN,id,CR_UNTRANSLATED,73.1,71.1,0.15);
		delay(4);
		setfont("GBLD3");  hudmessage(s:"A"; HUDMSG_PLAIN,id,CR_UNTRANSLATED,73.1,71.1,0.15);
		delay(4);
		setfont("GBLD4");  hudmessage(s:"A"; HUDMSG_PLAIN,id,CR_UNTRANSLATED,73.1,71.1,0.15);
		delay(4);
		setfont("GBLD5");  hudmessage(s:"A"; HUDMSG_PLAIN,id,CR_UNTRANSLATED,73.1,71.1,0.15);
		delay(4);
		setfont("GBLD6");  hudmessage(s:"A"; HUDMSG_PLAIN,id,CR_UNTRANSLATED,73.1,71.1,0.15);
		delay(4);
		setfont("GBLD7");  hudmessage(s:"A"; HUDMSG_PLAIN,id,CR_UNTRANSLATED,73.1,71.1,0.15);
		delay(4);
		setfont("GBLD8");  hudmessage(s:"A"; HUDMSG_PLAIN,id,CR_UNTRANSLATED,73.1,71.1,0.15);
		delay(4);
		setfont("GBLD9");  hudmessage(s:"A"; HUDMSG_PLAIN,id,CR_UNTRANSLATED,73.1,71.1,0.15);
		delay(4);
		setfont("GBLD10"); hudmessage(s:"A"; HUDMSG_PLAIN,id,CR_UNTRANSLATED,73.1,71.1,0.15);
		delay(4);
		setfont("GBLD11"); hudmessage(s:"A"; HUDMSG_PLAIN,id,CR_UNTRANSLATED,73.1,71.1,0.15);
		delay(4);
	}
	if (GetCvar("bd64_ScreenFX") == 2)
	{
		ACS_Execute(682,0,0,0,0);
	}
}

script 561 (void) CLIENTSIDE
{
	if (GetCvar("bd64_ScreenFX") == 1)
	{
		SetHudSize(400,250,1);
		int id = 561;

		delay(2);
		setfont("GBLD1");  hudmessage(s:"A"; HUDMSG_PLAIN,id,CR_UNTRANSLATED,0.9,30.9,0.15);
		delay(4);
		setfont("GBLD2");  hudmessage(s:"A"; HUDMSG_PLAIN,id,CR_UNTRANSLATED,0.9,30.9,0.15);
		delay(4);
		setfont("GBLD3");  hudmessage(s:"A"; HUDMSG_PLAIN,id,CR_UNTRANSLATED,0.9,30.9,0.15);
		delay(4);
		setfont("GBLD4");  hudmessage(s:"A"; HUDMSG_PLAIN,id,CR_UNTRANSLATED,0.9,30.9,0.15);
		delay(4);
		setfont("GBLD5");  hudmessage(s:"A"; HUDMSG_PLAIN,id,CR_UNTRANSLATED,0.9,30.9,0.15);
		delay(4);
		setfont("GBLD6");  hudmessage(s:"A"; HUDMSG_PLAIN,id,CR_UNTRANSLATED,0.9,30.9,0.15);
		delay(4);
		setfont("GBLD7");  hudmessage(s:"A"; HUDMSG_PLAIN,id,CR_UNTRANSLATED,0.9,30.9,0.15);
		delay(4);
		setfont("GBLD8");  hudmessage(s:"A"; HUDMSG_PLAIN,id,CR_UNTRANSLATED,0.9,30.9,0.15);
		delay(4);
		setfont("GBLD9");  hudmessage(s:"A"; HUDMSG_PLAIN,id,CR_UNTRANSLATED,0.9,30.9,0.15);
		delay(4);
		setfont("GBLD10"); hudmessage(s:"A"; HUDMSG_PLAIN,id,CR_UNTRANSLATED,0.9,30.9,0.15);
		delay(4);
		setfont("GBLD11"); hudmessage(s:"A"; HUDMSG_PLAIN,id,CR_UNTRANSLATED,0.9,30.9,0.15);
		delay(4);
	}
}

script 562 (void) CLIENTSIDE
{
	if (GetCvar("bd64_ScreenFX") == 1)
	{
		SetHudSize(400,250,1);
		int id = 562;

		delay(3);
		setfont("GBLD1");  hudmessage(s:"A"; HUDMSG_PLAIN,id,CR_UNTRANSLATED,263.1,81.1,0.15);
		delay(4);
		setfont("GBLD2");  hudmessage(s:"A"; HUDMSG_PLAIN,id,CR_UNTRANSLATED,263.1,81.1,0.15);
		delay(4);
		setfont("GBLD3");  hudmessage(s:"A"; HUDMSG_PLAIN,id,CR_UNTRANSLATED,263.1,81.1,0.15);
		delay(4);
		setfont("GBLD4");  hudmessage(s:"A"; HUDMSG_PLAIN,id,CR_UNTRANSLATED,263.1,81.1,0.15);
		delay(4);
		setfont("GBLD5");  hudmessage(s:"A"; HUDMSG_PLAIN,id,CR_UNTRANSLATED,263.1,81.1,0.15);
		delay(4);
		setfont("GBLD6");  hudmessage(s:"A"; HUDMSG_PLAIN,id,CR_UNTRANSLATED,263.1,81.1,0.15);
		delay(4);
		setfont("GBLD7");  hudmessage(s:"A"; HUDMSG_PLAIN,id,CR_UNTRANSLATED,263.9,81.9,0.15);
		delay(4);
		setfont("GBLD8");  hudmessage(s:"A"; HUDMSG_PLAIN,id,CR_UNTRANSLATED,263.9,81.9,0.15);
		delay(4);
		setfont("GBLD9");  hudmessage(s:"A"; HUDMSG_PLAIN,id,CR_UNTRANSLATED,263.9,81.9,0.15);
		delay(4);
		setfont("GBLD10"); hudmessage(s:"A"; HUDMSG_PLAIN,id,CR_UNTRANSLATED,263.9,81.9,0.15);
		delay(4);
		setfont("GBLD11"); hudmessage(s:"A"; HUDMSG_PLAIN,id,CR_UNTRANSLATED,263.9,81.9,0.15);
		delay(4);
	}
}

script 563 (void) CLIENTSIDE
{
	if (GetCvar("bd64_ScreenFX") == 1)
	{
		SetHudSize(400,250,1);
		int id = 563;

		delay(4);
		setfont("GBLD1");  hudmessage(s:"A"; HUDMSG_PLAIN,id,CR_UNTRANSLATED,123.1,-11.1,0.15);
		delay(4);
		setfont("GBLD2");  hudmessage(s:"A"; HUDMSG_PLAIN,id,CR_UNTRANSLATED,123.1,-11.1,0.15);
		delay(4);
		setfont("GBLD3");  hudmessage(s:"A"; HUDMSG_PLAIN,id,CR_UNTRANSLATED,123.1,-11.1,0.15);
		delay(4);
		setfont("GBLD4");  hudmessage(s:"A"; HUDMSG_PLAIN,id,CR_UNTRANSLATED,123.1,-11.1,0.15);
		delay(4);
		setfont("GBLD5");  hudmessage(s:"A"; HUDMSG_PLAIN,id,CR_UNTRANSLATED,123.1,-11.1,0.15);
		delay(4);
		setfont("GBLD6");  hudmessage(s:"A"; HUDMSG_PLAIN,id,CR_UNTRANSLATED,123.1,-11.1,0.15);
		delay(4);
		setfont("GBLD7");  hudmessage(s:"A"; HUDMSG_PLAIN,id,CR_UNTRANSLATED,123.9,-11.9,0.15);
		delay(4);
		setfont("GBLD8");  hudmessage(s:"A"; HUDMSG_PLAIN,id,CR_UNTRANSLATED,123.9,-11.9,0.15);
		delay(4);
		setfont("GBLD9");  hudmessage(s:"A"; HUDMSG_PLAIN,id,CR_UNTRANSLATED,123.9,-11.9,0.15);
		delay(4);
		setfont("GBLD10"); hudmessage(s:"A"; HUDMSG_PLAIN,id,CR_UNTRANSLATED,123.9,-11.9,0.15);
		delay(4);
		setfont("GBLD11"); hudmessage(s:"A"; HUDMSG_PLAIN,id,CR_UNTRANSLATED,123.9,-11.9,0.15);
		delay(4);
	}
}

script 564 (void) CLIENTSIDE
{
	if (GetCvar("bd64_ScreenFX") == 1)
	{
		SetHudSize(400,250,1);
		int id = 564;

		delay(4);
		setfont("GBLD1");  hudmessage(s:"A"; HUDMSG_PLAIN,id,CR_UNTRANSLATED,213.1,101.1,0.15);
		delay(4);
		setfont("GBLD2");  hudmessage(s:"A"; HUDMSG_PLAIN,id,CR_UNTRANSLATED,213.1,101.1,0.15);
		delay(4);
		setfont("GBLD3");  hudmessage(s:"A"; HUDMSG_PLAIN,id,CR_UNTRANSLATED,213.1,101.1,0.15);
		delay(4);
		setfont("GBLD4");  hudmessage(s:"A"; HUDMSG_PLAIN,id,CR_UNTRANSLATED,213.1,101.1,0.15);
		delay(4);
		setfont("GBLD5");  hudmessage(s:"A"; HUDMSG_PLAIN,id,CR_UNTRANSLATED,213.1,101.1,0.15);
		delay(4);
		setfont("GBLD6");  hudmessage(s:"A"; HUDMSG_PLAIN,id,CR_UNTRANSLATED,213.1,101.1,0.15);
		delay(4);
		setfont("GBLD7");  hudmessage(s:"A"; HUDMSG_PLAIN,id,CR_UNTRANSLATED,213.9,101.9,0.15);
		delay(4);
		setfont("GBLD8");  hudmessage(s:"A"; HUDMSG_PLAIN,id,CR_UNTRANSLATED,213.9,101.9,0.15);
		delay(4);
		setfont("GBLD9");  hudmessage(s:"A"; HUDMSG_PLAIN,id,CR_UNTRANSLATED,213.9,101.9,0.15);
		delay(4);
		setfont("GBLD10"); hudmessage(s:"A"; HUDMSG_PLAIN,id,CR_UNTRANSLATED,213.9,101.9,0.15);
		delay(4);
		setfont("GBLD11"); hudmessage(s:"A"; HUDMSG_PLAIN,id,CR_UNTRANSLATED,213.9,101.9,0.15);
		delay(4);
	}
}

script 565 (void) CLIENTSIDE
{
	if (GetCvar("bd64_ScreenFX") == 1)
	{
		SetHudSize(400,250,1);
		int id = 565;

		delay(4);
		setfont("GBLD1");  hudmessage(s:"A"; HUDMSG_PLAIN,id,CR_UNTRANSLATED,213.1,11.1,0.15);
		delay(4);
		setfont("GBLD2");  hudmessage(s:"A"; HUDMSG_PLAIN,id,CR_UNTRANSLATED,213.1,11.1,0.15);
		delay(4);
		setfont("GBLD3");  hudmessage(s:"A"; HUDMSG_PLAIN,id,CR_UNTRANSLATED,213.1,11.1,0.15);
		delay(4);
		setfont("GBLD4");  hudmessage(s:"A"; HUDMSG_PLAIN,id,CR_UNTRANSLATED,213.1,11.1,0.15);
		delay(4);
		setfont("GBLD5");  hudmessage(s:"A"; HUDMSG_PLAIN,id,CR_UNTRANSLATED,213.1,11.1,0.15);
		delay(4);
		setfont("GBLD6");  hudmessage(s:"A"; HUDMSG_PLAIN,id,CR_UNTRANSLATED,213.1,11.1,0.15);
		delay(4);
		setfont("GBLD7");  hudmessage(s:"A"; HUDMSG_PLAIN,id,CR_UNTRANSLATED,213.9,11.9,0.15);
		delay(4);
		setfont("GBLD8");  hudmessage(s:"A"; HUDMSG_PLAIN,id,CR_UNTRANSLATED,213.9,11.9,0.15);
		delay(4);
		setfont("GBLD9");  hudmessage(s:"A"; HUDMSG_PLAIN,id,CR_UNTRANSLATED,213.9,11.9,0.15);
		delay(4);
		setfont("GBLD10"); hudmessage(s:"A"; HUDMSG_PLAIN,id,CR_UNTRANSLATED,213.9,11.9,0.15);
		delay(4);
		setfont("GBLD11"); hudmessage(s:"A"; HUDMSG_PLAIN,id,CR_UNTRANSLATED,213.9,11.9,0.15);
		delay(4);
	}
}

//Pain Effect
script 530 (void) CLIENTSIDE
{
	SetHudSize(320,200,1);
	delay(1);
	setfont("PAIN1");
	hudmessage(s:"A"; HUDMSG_FADEOUT,530,CR_UNTRANSLATED,150.0,100.0,0.5);
	delay(4);
}

script 531 (void) CLIENTSIDE
{
	SetHudSize(320,200,1);
	delay(1);
	setfont("BREAK1");
	hudmessage(s:"A"; HUDMSG_FADEOUT,531,CR_UNTRANSLATED,150.0,100.0,0.6);
	delay(8);
	setfont("BREAK2");
	hudmessage(s:"A"; HUDMSG_FADEOUT,531,CR_UNTRANSLATED,150.0,100.0,0.5);
	delay(3);
}

script 532 (void) CLIENTSIDE
{
	SetHudSize(320,200,1);
	delay(1);
	setfont("BREAKS");
	hudmessage(s:"A"; HUDMSG_FADEOUT,532,CR_UNTRANSLATED,150.0,100.0,1.0);
	delay(10);
}

script 533 (void) CLIENTSIDE
{
	SetHudSize(320,200,1);
	delay(1);
	setfont("XBREAK");
	hudmessage(s:"A"; HUDMSG_FADEOUT,533,CR_UNTRANSLATED,150.0,100.0,4.0);
	delay(50);
}

script 611 (void) CLIENTSIDE
{
	SetHudSize(480,300,1);
	delay(1);
	setfont("PBULA1");
	hudmessage(s:"A"; HUDMSG_FADEOUT,611,CR_UNTRANSLATED,200.0,100.0,0.5);
	delay(8);
	setfont("PBULA2");
	hudmessage(s:"A"; HUDMSG_FADEOUT,611,CR_UNTRANSLATED,200.0,100.0,0.5);
	delay(8);
	setfont("PBULA3");
	hudmessage(s:"A"; HUDMSG_FADEOUT,611,CR_UNTRANSLATED,200.0,100.0,0.5);
	delay(8);
}

script 612 (void) CLIENTSIDE
{
	SetHudSize(480,300,1);
	delay(1);
	setfont("PBULB1");
	hudmessage(s:"A"; HUDMSG_FADEOUT,612,CR_UNTRANSLATED,200.0,100.0,0.5);
	delay(8);
	setfont("PBULB2");
	hudmessage(s:"A"; HUDMSG_FADEOUT,612,CR_UNTRANSLATED,200.0,100.0,0.5);
	delay(8);
	setfont("PBULB3");
	hudmessage(s:"A"; HUDMSG_FADEOUT,612,CR_UNTRANSLATED,200.0,100.0,0.5);
	delay(8);
}

script 613 (void) CLIENTSIDE
{
	SetHudSize(480,300,1);
	delay(1);
	setfont("PBULC1");
	hudmessage(s:"A"; HUDMSG_FADEOUT,613,CR_UNTRANSLATED,200.0,100.0,0.5);
	delay(8);
	setfont("PBULC2");
	hudmessage(s:"A"; HUDMSG_FADEOUT,613,CR_UNTRANSLATED,200.0,100.0,0.5);
	delay(8);
	setfont("PBULC3");
	hudmessage(s:"A"; HUDMSG_FADEOUT,613,CR_UNTRANSLATED,200.0,100.0,0.5);
	delay(8);
}

script 614 (void) CLIENTSIDE
{
	SetHudSize(480,300,1);
	delay(1);
	setfont("PBULD1");
	hudmessage(s:"A"; HUDMSG_FADEOUT,614,CR_UNTRANSLATED,200.0,100.0,0.5);
	delay(8);
	setfont("PBULD2");
	hudmessage(s:"A"; HUDMSG_FADEOUT,614,CR_UNTRANSLATED,200.0,100.0,0.5);
	delay(8);
	setfont("PBULD3");
	hudmessage(s:"A"; HUDMSG_FADEOUT,614,CR_UNTRANSLATED,200.0,100.0,0.5);
	delay(8);
}

script 615 (void) CLIENTSIDE
{
	SetHudSize(480,300,1);
	delay(1);
	setfont("PBULE1");
	hudmessage(s:"A"; HUDMSG_FADEOUT,615,CR_UNTRANSLATED,200.0,100.0,0.5);
	delay(8);
	setfont("PBULE2");
	hudmessage(s:"A"; HUDMSG_FADEOUT,615,CR_UNTRANSLATED,200.0,100.0,0.5);
	delay(8);
	setfont("PBULE3");
	hudmessage(s:"A"; HUDMSG_FADEOUT,615,CR_UNTRANSLATED,200.0,100.0,0.5);
	delay(8);
}

script 616 (void) CLIENTSIDE
{
	SetHudSize(480,300,1);
	delay(1);
	setfont("PBULF1");
	hudmessage(s:"A"; HUDMSG_FADEOUT,616,CR_UNTRANSLATED,200.0,100.0,0.5);
	delay(8);
	setfont("PBULF2");
	hudmessage(s:"A"; HUDMSG_FADEOUT,616,CR_UNTRANSLATED,200.0,100.0,0.5);
	delay(8);
	setfont("PBULF3");
	hudmessage(s:"A"; HUDMSG_FADEOUT,616,CR_UNTRANSLATED,200.0,100.0,0.5);
	delay(8);
}

script 617 (void) CLIENTSIDE
{
	SetHudSize(400,250,1);
	delay(4);
	setfont("SCRATCH");
	hudmessage(s:"A"; HUDMSG_PLAIN,617,CR_UNTRANSLATED,113.1,11.1,0.2);
	delay(4);
}

//Option
Script "ScreenEffects" (void)
{
	TakeInventory("ScreenFX",1);
	if (GetCvar("bd64_ScreenFX") == 2) { GiveInventory("ScreenFX",1); }
}

Script "BloodSplashTrail" (void)
{
	TakeInventory("BloodTrail",1);
	if (GetCvar("bd64_BloodTrail") == 1 || GetCvar("bd64_ScreenFX") == 2) { GiveInventory("BloodTrail",1); }
}