//Weapon & Item Spawner CVAR Checkers
script "ChaingunSpawnerACS" (void)		{ SetResultValue(GetCvar("Chaingun_Spawner_Cvar")); }
script "PlasmaRifleSpawnerACS" (void)	{ SetResultValue(GetCvar("PlasmaRifle_Spawner_Cvar")); }
script "BFGSpawnerACS" (void)			{ SetResultValue(GetCvar("BFG_Spawner_Cvar")); }
script "BonusRandomACS" (void)			{ SetResultValue(GetCvar("BonusRandomCvar")); }
script "WpnPowerRandomACS" (void)		{ SetResultValue(GetCvar("WpnPower_Spawner_Cvar")); }

//Monster Spawner Percentage CVAR Checker
script "MonstersSpawnPercentACS" (int Monster)
{
	static str _cvarprefixes[18] = {
	"Zombieman","ShotgunGuy","ChaingunGuy","Imp","Demon","Spectre","Cacodemon","LostSoul","PainElemental",
	"Arachnotron","HellKnight","Revenant","Baron","Mancubus","Archvile","Cyberdemon","Mastermind","Horde"
	};

	str cvarname = StrParam(s:"bd64_SpawnPercent",s:_cvarprefixes[Monster-1]);

	SetResultValue(GetCvar(cvarname));
}

//Monster Spawner CVAR Checkers
script "ZombiemanSpawnerACS" (void)		{ SetResultValue(GetCvar("Zombieman_Spawner_Cvar")); }
script "ShotgunGuySpawnerACS" (void)	{ SetResultValue(GetCvar("Shotgunguy_Spawner_Cvar")); }
script "ChaingunGuySpawnerACS" (void)	{ SetResultValue(GetCvar("Chaingunguy_Spawner_Cvar")); }
script "ImpSpawnerACS" (void)			{ SetResultValue(GetCvar("Imp_Spawner_Cvar")); }
script "DemonSpawnerACS" (void)			{ SetResultValue(GetCvar("Demon_Spawner_Cvar")); }
script "SpectreSpawnerACS" (void)		{ SetResultValue(GetCvar("Spectre_Spawner_Cvar")); }
script "CacodemonSpawnerACS" (void)		{ SetResultValue(GetCvar("Cacodemon_Spawner_Cvar")); }
script "BaronSpawnerACS" (void)			{ SetResultValue(GetCvar("Baron_Spawner_Cvar")); }
script "HoundChooserACS" (void)			{ SetResultValue(GetCvar("HoundChooserCvar")); }
script "RevenantSpawnerACS" (void)		{ SetResultValue(GetCvar("Revenant_Spawner_Cvar")); }
script "HellKnightSpawnerACS" (void)	{ SetResultValue(GetCvar("HellKnight_Spawner_Cvar")); }
script "FatsoSpawnerACS" (void)			{ SetResultValue(GetCvar("Fatso_Spawner_Cvar")); }
script "LostSoulSpawnerACS" (void)		{ SetResultValue(GetCvar("LostSoul_Spawner_Cvar")); }
script "ArachnotronSpawnerACS" (void)	{ SetResultValue(GetCvar("Arachnotron_Spawner_Cvar")); }
script "PainElementalSpawnerACS" (void)	{ SetResultValue(GetCvar("PainElemental_Spawner_Cvar")); }
script "ArchvileSpawnerACS" (void)		{ SetResultValue(GetCvar("Archvile_Spawner_Cvar")); }
script "CyberdemonSpawnerACS" (void)	{ SetResultValue(GetCvar("Cyberdemon_Spawner_Cvar")); }
script "MastermindSpawnerACS" (void)	{ SetResultValue(GetCvar("Mastermind_Spawner_Cvar")); }
script "HordeMultiplierACS" (void)		{ SetResultValue(GetCvar("TheHorde_Multiplier_Cvar")); }

//Base WAD Compatibility Checker
script "WADCheckerACS" (void)			{ SetResultValue(GetCvar("WADCheckerCvar")); }

//Environment & Prop Checkers
script "PoltergeistEnablerACS" (void)	{ SetResultValue(GetCvar("PoltergeistCvar")); }
script "ThingRandomACS" (void)			{ SetResultValue(GetCvar("ThingRandomCvar")); }
script "CacoChooserACS" (void)			{ SetResultValue(GetCvar("CacoChooserCvar")); }