//Presets
script "DefaultCvars" (void) net
{
	SetCVarString("BD64_Preset","Default");

	SetCvar("AlternativeAmmoPickupSpritesCvar",1);
	SetCvar("VanillaChainsawCvar",0);
	SetCvar("ClassicChaingunCvar",0);
	SetCvar("ClassicRLCvar",0);
	SetCvar("VWeaponCvar",0);
	SetCvar("WeaponsWarmUpCvar",1);
	SetCvar("CensoredHealing_Cvar",0);
	SetCvar("AlphaPickupCvar",0);
	SetCvar("FlashlightStartCvar",0);
	SetCvar("NoReloadCvar",0);

	SetCvar("D64_SkipTitleMap",0);
	SetCvar("VMapCheckCvar",0);
	SetCvar("TCMapCheckCvar",1);
	SetCvar("AbsMapCheckCvar",1);

	SetCvar("Chaingun_Spawner_Cvar",1);
	SetCvar("PlasmaRifle_Spawner_Cvar",1);
	SetCvar("BFG_Spawner_Cvar",1);
	SetCvar("WpnPower_Spawner_Cvar",1);
	SetCvar("BonusRandomCvar",1);

	SetCvar("Zombieman_Spawner_Cvar",1);
	SetCvar("Shotgunguy_Spawner_Cvar",1);
	SetCvar("Chaingunguy_Spawner_Cvar",1);
	SetCvar("Imp_Spawner_Cvar",1);
	SetCvar("Demon_Spawner_Cvar",1);
	SetCvar("Spectre_Spawner_Cvar",1);
	SetCvar("Cacodemon_Spawner_Cvar",1);
	SetCvar("LostSoul_Spawner_Cvar",1);
	SetCvar("Arachnotron_Spawner_Cvar",1);
	SetCvar("HellKnight_Spawner_Cvar",1);
	SetCvar("Revenant_Spawner_Cvar",1);
	SetCvar("Baron_Spawner_Cvar",1);
	SetCvar("Fatso_Spawner_Cvar",1);
	SetCvar("PainElemental_Spawner_Cvar",1);
	SetCvar("Archvile_Spawner_Cvar",1);
	SetCvar("Cyberdemon_Spawner_Cvar",1);
	SetCvar("Mastermind_Spawner_Cvar",1);

	SetCvar("CacoChooserCvar",0);
	SetCvar("HoundChooserCvar",1);

	SetCvar("HUDSwitchCvar",0);
	SetCvar("FootStepCheckCvar",0);
	SetCvar("LFog_Cvar",0);
	SetCvar("FlatDecalCvar",1);
	SetCvar("ClassicTorchCvar",0);
	SetCvar("LiquidSplashCvar",0);

	SetCvar("PoltergeistCvar",1);
	SetCvar("ThingRandomCvar",1);
	SetCvar("TheHorde_Multiplier_Cvar",-1);
	
	SetUserCvar(PlayerNumber(),"AlternativeLaserSkinCvar",TRUE);
	SetUserCvar(PlayerNumber(),"BerserkSwitchFistsCvar",TRUE);
	SetUserCvar(PlayerNumber(),"LowAmmoSFX",1);
	ACS_NamedExecuteAlways("BD64Respawn",0);
	
	//percent is here
	SetCvar("bd64_SpawnPercentZombieman",1);
	SetCvar("bd64_SpawnPercentShotgunGuy",1);
	SetCvar("bd64_SpawnPercentChaingunGuy",1);
	SetCvar("bd64_SpawnPercentImp",1);
	SetCvar("bd64_SpawnPercentDemon",1);
	SetCvar("bd64_SpawnPercentSpectre",1);
	SetCvar("bd64_SpawnPercentCacodemon",1);
	SetCvar("bd64_SpawnPercentLostSoul",1);
	SetCvar("bd64_SpawnPercentPainElemental",1);
	SetCvar("bd64_SpawnPercentArachnotron",1);
	SetCvar("bd64_SpawnPercentHellKnight",1);
	SetCvar("bd64_SpawnPercentRevenant",1);
	SetCvar("bd64_SpawnPercentBaron",1);
	SetCvar("bd64_SpawnPercentMancubus",1);
	SetCvar("bd64_SpawnPercentArchvile",1);
	SetCvar("bd64_SpawnPercentCyberdemon",1);
	SetCvar("bd64_SpawnPercentMastermind",1);
	SetCvar("bd64_SpawnPercentHorde",1);
	
	delay(1);
}

script "ClassicalCvars" (void) net
{
	SetCVarString("BD64_Preset","Classical");
	
	SetCvar("AlternativeAmmoPickupSpritesCvar",1);
	SetCvar("VanillaChainsawCvar",1);
	SetCvar("ClassicChaingunCvar",1);
	SetCvar("ClassicRLCvar",1);
	SetCvar("VWeaponCvar",1);
	SetCvar("WeaponsWarmUpCvar",0);
	SetCvar("CensoredHealing_Cvar",0);
	SetCvar("AlphaPickupCvar",0);
	SetCvar("FlashlightStartCvar",0);
	SetCvar("NoReloadCvar",1);

	SetCvar("D64_SkipTitleMap",0);
	SetCvar("VMapCheckCvar",1);
	SetCvar("TCMapCheckCvar",0);
	SetCvar("AbsMapCheckCvar",0);

	SetCvar("CacoChooserCvar",0);
	SetCvar("HoundChooserCvar",-1);

	SetCvar("Chaingun_Spawner_Cvar",1);
	SetCvar("PlasmaRifle_Spawner_Cvar",1);
	SetCvar("BFG_Spawner_Cvar",1);
	SetCvar("WpnPower_Spawner_Cvar",1);
	SetCvar("BonusRandomCvar",1);

	SetCvar("Zombieman_Spawner_Cvar",1);
	SetCvar("Shotgunguy_Spawner_Cvar",1);
	SetCvar("Chaingunguy_Spawner_Cvar",1);
	SetCvar("Imp_Spawner_Cvar",1);
	SetCvar("Demon_Spawner_Cvar",1);
	SetCvar("Spectre_Spawner_Cvar",1);
	SetCvar("Cacodemon_Spawner_Cvar",1);
	SetCvar("LostSoul_Spawner_Cvar",1);
	SetCvar("Arachnotron_Spawner_Cvar",1);
	SetCvar("HellKnight_Spawner_Cvar",1);
	SetCvar("Revenant_Spawner_Cvar",-1);
	SetCvar("Baron_Spawner_Cvar",1);
	SetCvar("Fatso_Spawner_Cvar",1);
	SetCvar("PainElemental_Spawner_Cvar",1);
	SetCvar("Archvile_Spawner_Cvar",-4);
	SetCvar("Cyberdemon_Spawner_Cvar",1);
	SetCvar("Mastermind_Spawner_Cvar",-4);

	SetCvar("TheHorde_Multiplier_Cvar",-1);

	SetCvar("HUDSwitchCvar",0);
	SetCvar("FootStepCheckCvar",1);
	SetCvar("LFog_Cvar",1);
	SetCvar("FlatDecalCvar",0);
	SetCvar("ClassicTorchCvar",1);
	SetCvar("LiquidSplashCvar",1);

	SetCvar("PoltergeistCvar",0);
	SetCvar("ThingRandomCvar",0);

	SetUserCvar(PlayerNumber(),"AlternativeLaserSkinCvar",FALSE);
	SetUserCvar(PlayerNumber(),"BerserkSwitchFistsCvar",1);
	SetUserCvar(PlayerNumber(),"LowAmmoSFX",0);
	ACS_NamedExecuteAlways("BD64Respawn",0);
	
	//percent is here
	SetCvar("bd64_SpawnPercentZombieman",1);
	SetCvar("bd64_SpawnPercentShotgunGuy",1);
	SetCvar("bd64_SpawnPercentChaingunGuy",1);
	SetCvar("bd64_SpawnPercentImp",1);
	SetCvar("bd64_SpawnPercentDemon",1);
	SetCvar("bd64_SpawnPercentSpectre",1);
	SetCvar("bd64_SpawnPercentCacodemon",1);
	SetCvar("bd64_SpawnPercentLostSoul",1);
	SetCvar("bd64_SpawnPercentPainElemental",1);
	SetCvar("bd64_SpawnPercentArachnotron",1);
	SetCvar("bd64_SpawnPercentHellKnight",1);
	SetCvar("bd64_SpawnPercentRevenant",1);
	SetCvar("bd64_SpawnPercentBaron",1);
	SetCvar("bd64_SpawnPercentMancubus",1);
	SetCvar("bd64_SpawnPercentArchvile",1);
	SetCvar("bd64_SpawnPercentCyberdemon",1);
	SetCvar("bd64_SpawnPercentMastermind",1);
	SetCvar("bd64_SpawnPercentHorde",1);
	
	delay(1);
}

script "StevenCvars" (void) net
{
	SetCVarString("BD64_Preset","SWC's Vision");
	
	SetCvar("AlternativeAmmoPickupSpritesCvar",2);
	SetCvar("VanillaChainsawCvar",0);
	SetCvar("ClassicChaingunCvar",0);
	SetCvar("ClassicRLCvar",0);
	SetCvar("VWeaponCvar",0);
	SetCvar("WeaponsWarmUpCvar",1);
	SetCvar("CensoredHealing_Cvar",0);
	SetCvar("AlphaPickupCvar",1);
	SetCvar("FlashlightStartCvar",0);
	SetCvar("NoReloadCvar",0);

	SetCvar("D64_SkipTitleMap",0);
	SetCvar("VMapCheckCvar",0);
	SetCvar("TCMapCheckCvar",1);
	SetCvar("AbsMapCheckCvar",1);

	SetCvar("Chaingun_Spawner_Cvar",0);
	SetCvar("PlasmaRifle_Spawner_Cvar",0);
	SetCvar("BFG_Spawner_Cvar",0);
//	SetCvar("WpnPower_Spawner_Cvar",0);
	SetCvar("BonusRandomCvar",0);

	SetCvar("Zombieman_Spawner_Cvar",0);
	SetCvar("Shotgunguy_Spawner_Cvar",0);
	SetCvar("Chaingunguy_Spawner_Cvar",0);
	SetCvar("Imp_Spawner_Cvar",0);
	SetCvar("Demon_Spawner_Cvar",0);
	SetCvar("Spectre_Spawner_Cvar",0);
	SetCvar("Cacodemon_Spawner_Cvar",0);
	SetCvar("LostSoul_Spawner_Cvar",0);
	SetCvar("Arachnotron_Spawner_Cvar",0);
	SetCvar("HellKnight_Spawner_Cvar",0);
	SetCvar("Revenant_Spawner_Cvar",0);
	SetCvar("Baron_Spawner_Cvar",0);
	SetCvar("Fatso_Spawner_Cvar",0);
	SetCvar("PainElemental_Spawner_Cvar",0);
	SetCvar("Archvile_Spawner_Cvar",0);
	SetCvar("Cyberdemon_Spawner_Cvar",0);
	SetCvar("Mastermind_Spawner_Cvar",0);

	SetCvar("CacoChooserCvar",1);
	SetCvar("HoundChooserCvar",2);

	SetCvar("HUDSwitchCvar",1);
	SetCvar("FootStepCheckCvar",0);
	SetCvar("LFog_Cvar",0);
	SetCvar("FlatDecalCvar",1);
	SetCvar("ClassicTorchCvar",0);
	SetCvar("LiquidSplashCvar",0);

	SetCvar("PoltergeistCvar",1);
	SetCvar("ThingRandomCvar",1);
	SetCvar("TheHorde_Multiplier_Cvar",0);
	
	SetUserCvar(PlayerNumber(),"AlternativeLaserSkinCvar",TRUE);
	SetUserCvar(PlayerNumber(),"BerserkSwitchFistsCvar",TRUE);
	SetUserCvar(PlayerNumber(),"LowAmmoSFX",1);
	ACS_NamedExecuteAlways("BD64Respawn",0);
	
	//percent is here
	SetCvar("bd64_SpawnPercentZombieman",4);
	SetCvar("bd64_SpawnPercentShotgunGuy",4);
	SetCvar("bd64_SpawnPercentChaingunGuy",4);
	SetCvar("bd64_SpawnPercentImp",5);
	SetCvar("bd64_SpawnPercentDemon",5);
	SetCvar("bd64_SpawnPercentSpectre",4);
	SetCvar("bd64_SpawnPercentCacodemon",3);
	SetCvar("bd64_SpawnPercentLostSoul",2);
	SetCvar("bd64_SpawnPercentPainElemental",2);
	SetCvar("bd64_SpawnPercentArachnotron",2);
	SetCvar("bd64_SpawnPercentHellKnight",4);
	SetCvar("bd64_SpawnPercentRevenant",5);
	SetCvar("bd64_SpawnPercentBaron",4);
	SetCvar("bd64_SpawnPercentMancubus",4);
	SetCvar("bd64_SpawnPercentArchvile",3);
	SetCvar("bd64_SpawnPercentCyberdemon",6);
	SetCvar("bd64_SpawnPercentMastermind",6);
	SetCvar("bd64_SpawnPercentHorde",10);
	
	delay(1);
}